---
title: "05 SCRNA All"
output: html_notebook
---

```{r}

SEURAT_RDS_FILE <- here::here(
    '..','..','scrnaseq_tcsl154',
    'rds','scrna.hashed.rds')

# scrna <- subset(
#   readRDS(SEURAT_RDS_FILE),
#   subset=(car != 'K_only'))

source(here::here('r','scrna','scrna_analysis_fxns.R'))
source(here::here('r','fig_colors.R'))
```

## Cell Cycle Regression, SCTransform, WNN

```{r}
#score on cell cycle

#RNA
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
DefaultAssay(scrna) <- 'RNA'
scrna <- CellCycleScoring(scrna, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

scrna <- SCTransform(scrna, assay='RNA', 
  vars.to.regress = c("S.Score", "G2M.Score"))
scrna <- RunPCA(scrna, assay='SCT', features = VariableFeatures(scrna), nfeatures.print = 10, 
    reduction.name='sct_rna_pca')

#ADT
DefaultAssay(scrna) <- 'ADT'
scrna <- SCTransform(scrna, assay='ADT', new.assay.name = 'SCT_ADT', 
  vars.to.regress = c("S.Score", "G2M.Score"))
scrna <- RunPCA(scrna, assay='SCT_ADT', features = rownames(scrna[["SCT_ADT"]]), nfeatures.print = 10, 
    reduction.name='sct_adt_pca')

scrna <- FindMultiModalNeighbors(
  scrna, reduction.list = list("sct_rna_pca", "adt_pca"), 
  dims.list = list(1:30, 1:18), modality.weight.name = "RNA.weight"
)

# Perform Clustering
cluster_resolution <- 1.3
cluster_name <- paste0('wsnn_res.',as.character(cluster_resolution))
scrna <- RunUMAP(scrna, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
scrna <- FindClusters(scrna, graph.name = "wsnn", algorithm = 3, resolution = cluster_resolution, verbose = FALSE)
```

```{r}
p1 <- DimPlot(scrna, reduction = 'wnn.umap', label = TRUE, repel = TRUE, label.size = 2.5) + NoLegend()
p2 <- DimPlot(scrna, reduction = 'wnn.umap', group.by = 'car', label = TRUE, repel = TRUE, label.size = 2.5,
  cols=c(car_colors, '4-1BB'=car_colors[['41BB']], 'Untransduced'='grey60'))
p3 <- DimPlot(scrna, reduction = 'wnn.umap', group.by = 'k_type', label = TRUE, repel = TRUE, label.size = 2.5) + NoLegend()
p4 <- DimPlot(scrna, reduction = 'wnn.umap', group.by = 'Phase', label = TRUE, repel = TRUE, label.size = 2.5) + NoLegend()
p1 + p3 + p4 + p2

p1 <- DimPlot(scrna, reduction = 'wnn.umap', label = TRUE, repel = TRUE, label.size = 2.5) + NoLegend()
p2 <- DimPlot(scrna, reduction = 'wnn.umap', group.by = 'car', label = TRUE, repel = TRUE, label.size = 2.5)
p3 <- DimPlot(scrna, reduction = 'wnn.umap', group.by = 'k_type', label = TRUE, repel = TRUE, label.size = 2.5) + NoLegend()
p4 <- DimPlot(scrna, reduction = 'wnn.umap', group.by = 'Phase', label = TRUE, repel = TRUE, label.size = 2.5) + NoLegend()
p1 + p3 + p4 + p2


DefaultAssay(scrna) <- 'SCT_ADT'
adt_markers <- FindAllMarkers(scrna, features = VariableFeatures(scrna), min.pct = 0.25, logfc.threshold = 0.25)



scrna_umap_plot_adt <- umap_plot(scrna, plot_title_text="CD8, CD19+ ADT WNN", assay='SCT_ADT', cluster_name=cluster_name, reduction= 'wnn.umap')
scrna_umap_plot_adt$umap_plots
FeaturePlot(scrna, features=paste(c('CD62L','CD45RO','CD30','CD137','HLA-ABC','CD49b','CD80','CD7','LAG3','Tim3','CD32','CTLA4'),'adt',sep='.'), label=T)

DefaultAssay(scrna) <- 'SCT'
scrna_umap_plot <- umap_plot(scrna, plot_title_text="CD8, CD19+ RNA WNN", assay='SCT', cluster_name=cluster_name, reduction= 'wnn.umap')
scrna_umap_plot$umap_plots
FeaturePlot(scrna, features=c('CD62L','CD45RO','CD30','CD137','HLA-ABC','CD49b','CD80','CD7','LAG3','Tim3','CD32','CTLA4'), label=T)
```


```{r}

plot_clust_by_act <- function(seurat_obj, cluster_name='seurat_clusters') {

    car_clust_data <- data.table(
      seurat_obj@meta.data)[, list(n_clust_car= .N), 
      by=c(cluster_name, "car", "k_type")][, 
        pct_clust_car := n_clust_car/sum(n_clust_car), 
        by=.(car, k_type)][,
          cd19_clust_car_l2fc := log2(
              pct_clust_car[k_type == 'cd19+']/pct_clust_car[k_type == 'baseline']), 
          by=.(get(cluster_name), car)][, 
            cd19_clust_act_l2fc := mean(
                cd19_clust_car_l2fc[!(car %in% c('KLRG1','Untransduced'))], na.rm=T), 
            by=get(cluster_name)]
    
    car_clust_data[, pct_clust_car_max := max(pct_clust_car), by=.(get(cluster_name), car)]
    car_clust_data[, is_act := max(pct_clust_car) > pct_clust_car[k_type == 'baseline'], 
        by=.(get(cluster_name), car)]
    car_clust_data[is.na(is_act), is_act := T]
    car_clust_data[, is_act_avg := sum(is_act) > length(unique(car)), by=.(get(cluster_name))]
    
    clust_pt_plot <- ggplot(car_clust_data) + 
        geom_point(
            aes(x=get(cluster_name), y=car, fill=cd19_clust_car_l2fc, size=pct_clust_car_max), shape=21) + 
        scale_fill_distiller(palette='PRGn', direction=1) + scale_size_area(max_size=12) + 
        theme_minimal() + 
        facet_grid(~is_act_avg, scales='free')
    
    activation_colors <- ggplot_build(
      ggplot(unique(car_clust_data[, list(cd19_clust_act_l2fc, seurat_clusters)])) + 
      geom_tile(aes(x=get(cluster_name), y='1', fill=cd19_clust_act_l2fc)) + 
      scale_fill_distiller(palette='PRGn', direction=1))$data[1][[1]][c('fill','x')]
    
    act_dimplot <- DimPlot(seurat_obj,
        cols=activation_colors$fill[order(activation_colors$x)], label=T)
    
    return(list(
        clust_pt_plot=clust_pt_plot,
        activation_colors=activation_colors,
        act_dimplot=act_dimplot))
}
```