---
title: "TCSL155 - K562 In Vivo Growth Curves"
output:
  html_document:
    df_print: paged
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here('..','html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)
library(cowplot)
```

```{r cars, fig.width=10, fig.height=6}
growth_dt <- fread("~/s3-roybal-tcsl/lenti_screen_compiled_data/data/invivo/tcsl155_growth.csv")

growth_dt <- rbind(
    unique(growth_dt[, list(
        day=0, cage, mouse, car, 
        length=0, width=0, height=0, 
        notes='', Area=0, Area2=0)]),
    growth_dt)

growth_summ_dt <- data.table(growth_dt)[!is.na(Area), {
    bps= boxplot.stats(log(Area))$stats
    list(var='Area', lo=bps[1],lhinge=bps[2],uhinge=bps[3],hi=bps[4], sd=sd(Area))
    },
    by=.(car, day)]

growth_summ_dt <- rbind(growth_summ_dt, 
    data.table(growth_dt)[!is.na(Area2), {
        bps= boxplot.stats(log(Area2))$stats
        list(var='Area2', lo=bps[1],lhinge=bps[2],uhinge=bps[3],hi=bps[4], sd=sd(Area))
        },
        by=.(car, day)]
    )

growth_summ_dt[day==0, lo := -Inf]

plot_grid(
    ggplot(
            growth_dt[day>0], aes(x=car, y=Area, color=day, group=interaction(day, car)), position='dodge') + 
        geom_boxplot() + 
        geom_point(position = position_jitterdodge()) + theme_bw(),
    ggplot(
            growth_dt[day>0], aes(x=car, y=Area2, color=day, group=interaction(day, car)), position='dodge') + 
        geom_boxplot() + 
        geom_point(position = position_jitterdodge()) + theme_bw(),
    ncol=2, labels=c('Area=0.5 x LWD','Area=0.5 x LWW'))
    
plot_grid(
    ggplot(
            growth_dt,
            aes(y=log(Area), x=day, color=car, group=interaction(mouse, cage))) + 
        geom_line(show.legend = FALSE) + 
        facet_wrap(.~car) +
        theme_bw(),
    ggplot(
            growth_dt,
            aes(y=log(Area2), x=day, color=car, group=interaction(mouse, cage))) + 
        geom_line(show.legend = FALSE) + 
        facet_wrap(.~car) +
        theme_bw(), 
    scale=0.9,
    ncol=2, nrow=1, labels=c('Area=0.5 x LWD','Area=0.5 x LWW'))

growth_dt[day  > 0, Area_from_d11 := Area - Area[day == 11], by=.(mouse, cage)]
growth_dt[day  > 0, Area2_from_d11 := Area2 - Area2[day == 11], by=.(mouse, cage)]

plot_grid(
    ggplot(
            growth_dt,
            aes(y=log(Area_from_d11), x=day, color=car, group=interaction(mouse, cage))) + 
        geom_line(show.legend = FALSE) + 
        facet_wrap(.~car) +
        theme_bw(),
    ggplot(
            growth_dt,
            aes(y=log(Area2_from_d11), x=day, color=car, group=interaction(mouse, cage))) + 
        geom_line(show.legend = FALSE) + 
        facet_wrap(.~car) +
        theme_bw(), 
    scale=0.9,
    ncol=2, nrow=1, labels=c('Area, vs d11=0.5 x LWD','Area, vs d11=0.5 x LWW'))

plot_grid(
    ggplot(
            growth_dt,
            aes(y=Area, x=day, color=car, group=interaction(mouse, cage))) + 
        geom_line(show.legend = FALSE) + 
        facet_wrap(.~car) +
        theme_bw(),
    ggplot(
            growth_dt,
            aes(y=Area2, x=day, color=car, group=interaction(mouse, cage))) + 
        geom_line(show.legend = FALSE) + 
        facet_wrap(.~car) +
        theme_bw(), 
    scale=0.9,
    ncol=2, nrow=1, labels=c('Area=0.5 x LWD','Area=0.5 x LWW'))
```