---
title: "BCMA BAFFR Plots"
output: html_notebook

```{r}
library(ggplot2)
library(data.table)
library(patchwork)
library(cowplot)
library(tidyverse)

# load colors
source(here::here("r",'fig_colors.R'))


# load measurements
tumor_measurements_fn <- here::here("r","in_vivo","bcma",'bcma.data.csv')

tumor_measurements <- fread(tumor_measurements_fn)

# remove values where there is nothing written in the avg.radiance (aka when the mouse died)
tumor_measurements <- tumor_measurements[avg.radiance != 'NA']


##plot each mouse individually by group
plot.data <- tumor_measurements[day<32 &
  scfv!="BC50" & scfv!="BC30" &
  costim!="Zeta" & costim!="PBS"]
  
#rename baffr to work with CAR colors
plot.data[costim=='BAFFR', costim := 'BAFF-R']

##this is fixing it so that we incorporate trac ko as the same color as unt. 
##first we find what costims are unique
plot_car_colors <- car_colors[unique(plot.data$costim)]
#remove na because that's what trac ko becomes
plot_car_colors <- plot_car_colors[!is.na(plot_car_colors)]
#assign it the right color from original choices
plot_car_colors['TRAC KO'] <- car_colors['Unt']

#this changes the order that it shows the plots in within ggplot
plot.data[, costim := 
  factor(costim, levels=c("41BB", "CD28", "BAFF-R", "TRAC KO"))]

tumor_growth_plot <- ggplot(plot.data,
    aes(y=(avg.radiance), x=day, color=costim,
        group=interaction(exp.num, scfv, costim, mouse.num),
        linetype=factor(exp.num))) + 
          ## line type is the dashed vs solid. solid is linetype 1
    geom_line() +
    geom_point() + 
    scale_y_log10(
      breaks = trans_breaks("log10", function(x) 10^x),
      labels = trans_format("log10", math_format(10^.x))) +
    scale_color_manual(values=plot_car_colors) +
    theme_minimal() +
    labs(
      title="BCMA MM1S Tumor Growth Curves",
      x="Days Post T cell Injection",
      y="Radiance (log10)",
      color='Costim Domains',
      linetype='Donor')+
    facet_wrap(c("costim"), ncol=4) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      #axis.line = element_line(colour = "black"),
      plot.title = element_text(hjust = 0.5),
      panel.border=element_rect(color='black', fill=NA))
```


## Mixed Effects Model, Repeated Measures
```{r}

library(nlme)

rad_me_data <- plot.data[,
    list(exp.num, costim=relevel(costim, ref='TRAC KO'),
    mouse.num=factor(paste(mouse.num, exp.num, sep='.')), 
    log2.rad= log2(avg.radiance), 
    day=ordered(day))]
    
with(rad_me_data, {
  nestinginfo <- groupedData(log2.rad ~ costim | mouse.num,
    outer = ~ exp.num,
    data= rad_me_data)
  fit.compsym <- gls(log2.rad ~ costim * day,
    data=nestinginfo,
    corr=corCompSymm(, form= ~ 1 | mouse.num))
  fit.ar1 <- gls(log2.rad ~ costim * day,
    data=nestinginfo,
    corr=corAR1(, form= ~ 1 | mouse.num))
  fit.ar1het <- gls(log2.rad ~ costim * day,
    data=nestinginfo,
    corr=corAR1(, form= ~ 1 | mouse.num),
    weights=varIdent(form = ~ 1 | exp.num))
  
  # compare models for AIC and loglik
  print(anova(fit.compsym, fit.ar1, fit.ar1het)) #compares the models
  print(anova(fit.compsym))
  print(anova(fit.ar1))
  print(anova(fit.ar1het))
})

# AR1 covariance structure gave lowest AIC and loglik, so using that
compute_pairwise_mixed_effects <- function(data) {
  glsControl(maxIter=1000, msMaxIter=1000, tolerance=1e-3)
  with(data, tryCatch({
    
    print(paste(unique(data$costim), collapse='.'))
    
    nestinginfo <- groupedData(log2.rad ~ costim | exp.num/mouse.num,
    data= data)

    fit.ar1 <- gls(log2.rad ~ costim * day,
      data=nestinginfo,
      corr=corAR1(, form= ~ 1 | mouse.num))
        
    return(list(costim=paste(unique(data$costim), collapse='.'), 
      model=fit.ar1))},
    
    error=function(cond) {
      
      message("Here's the original error message:")
      message(cond)
      return(NA)
    }))
}

models <- apply(rad_me_data[, combn(unique(costim),2)], 2,
  function(x) compute_pairwise_mixed_effects(rad_me_data[costim %in% x]))
  
p_values <- data.table(t(sapply(models, function(model_i) c(model_i$cars, anova(model_i$model)$`p-value`[4]))))
names(p_values) <- c('car_1','car_2','pvalue')
p_values[, pvalue := as.numeric(pvalue)] 
p_values[, car_1 := factor(car_1, levels=growth_dt[, unique(car)])]
p_values[, car_2 := factor(car_2, levels=growth_dt[, unique(car)])]


models_cd8 <- lapply(prolif_data_raw[,unique(CAR.align)],
  function(x) compute_pairwise_mixed_effects(prolif_data_raw[t.type=='CD8'], x))
for (i in seq(length(models_cd8))) models_cd8[[i]]$t.type = 'CD8'

models_cd4 <- lapply(prolif_data_raw[,unique(CAR.align)],
  function(x) compute_pairwise_mixed_effects(prolif_data_raw[t.type=='CD4'], x))
for (i in seq(length(models_cd4))) models_cd4[[i]]$t.type = 'CD4'

models_combined <- lapply(prolif_data_raw[,unique(CAR.align)],
  function(x) compute_pairwise_mixed_effects(prolif_data_raw, x))
for (i in seq(length(models_combined))) models_combined[[i]]$t.type = 'both'

p_values <- data.table(t(sapply(
  c(models_cd8, models_cd4, models_combined),
    function(model_i) c(
      CAR.align=as.character(model_i$car),
      t.type=model_i$t.type,
      pval=as.numeric(anova(model_i$model)$`p-value`[2]),
      coef=as.numeric(model_i$model$coefficients[2])))))
p_values[, coef := as.numeric(coef)]
p_values[, pval := as.numeric(pval)]
p_values[, CAR.align := factor(CAR.align)]
p_values[, padj := p.adjust(as.numeric(pval), 'BH'), by='t.type']

```


```{r}
rad_me_expanded <- rad_me_data[, 
  expand.grid(day=unique(day),mouse.num= unique(mouse.num))]

rad_me_data_interpolated <- rad_me_data[rad_me_expanded,  
  on=.(day, mouse.num), nomatch=NA]
  
setorderv(rad_me_data_interpolated, c("mouse.num","day"))

rad_me_data_interpolated[, exp.num := na.omit(unique(exp.num)), by=mouse.num]
rad_me_data_interpolated[, costim := na.omit(unique(costim)), by=mouse.num]

# interpolate missing days linearly
rad_me_data_interpolated[,
  log2.rad.interpolated := na.approx(log2.rad[order(day)], na.rm=F),
  by=mouse.num]  
  
# relative to earliest day with data
rad_me_data_interpolated[, 
  log2.rad.interpolated.rel := (
    log2.rad.interpolated - log2.rad.interpolated[
      day==min(day[!is.na(log2.rad.interpolated)])]),
  by=.(mouse.num)]
  
library(nlme)
    
with(rad_me_data_interpolated, {
  nestinginfo <- groupedData(log2.rad.interpolated.rel ~ costim | mouse.num,
    outer = ~ exp.num,
    data= rad_me_data_interpolated[!is.na(log2.rad.interpolated.rel)])
  fit.compsym <- gls(log2.rad.interpolated.rel ~ costim * day,
    data=nestinginfo,
    corr=corCompSymm(, form= ~ 1 | mouse.num))
  fit.ar1 <- gls(log2.rad.interpolated.rel ~ costim * day,
    data=nestinginfo,
    corr=corAR1(, form= ~ 1 | mouse.num))
  fit.ar1het <- gls(log2.rad.interpolated.rel ~ costim * day,
    data=nestinginfo,
    corr=corAR1(, form= ~ 1 | mouse.num),
    weights=varIdent(form = ~ 1 | exp.num))
  
  # compare models for AIC and loglik
  print(anova(fit.compsym, fit.ar1, fit.ar1het)) #compares the models
  print(anova(fit.compsym))
  print(anova(fit.ar1))
  print(anova(fit.ar1het))
})

# AR1 covariance structure gave lowest AIC and loglik, so using that
compute_pairwise_mixed_effects <- function(data) {
  glsControl(maxIter=1000, msMaxIter=1000, tolerance=1e-3)
  with(data, tryCatch({
    
    print(paste(unique(data$costim), collapse='.'))
    
    nestinginfo <- groupedData(log2.rad.interpolated.rel ~ costim | exp.num/mouse.num,
      data= data[!is.na(log2.rad.interpolated.rel)])

    fit.compsym <- gls(log2.rad.interpolated.rel ~ costim * day,
    data=nestinginfo,
    corr=corCompSymm(, form= ~ 1 | mouse.num))
        
    return(list(costim=paste(unique(data$costim), collapse='.'), 
      model=fit.compsym))},
    
    error=function(cond) {
      
      message("Here's the original error message:")
      message(cond)
      return(NA)
    }))
}

models <- apply(rad_me_data_interpolated[, combn(unique(costim),2)], 2,
  function(x) compute_pairwise_mixed_effects(rad_me_data_interpolated[costim %in% x]))
  
p_values <- data.table(t(sapply(models, function(model_i) c(model_i$cars, anova(model_i$model)$`p-value`[4]))))
names(p_values) <- c('car_1','car_2','pvalue')
p_values[, pvalue := as.numeric(pvalue)] 
p_values[, car_1 := factor(car_1, levels=growth_dt[, unique(car)])]
p_values[, car_2 := factor(car_2, levels=growth_dt[, unique(car)])]


models_cd8 <- lapply(prolif_data_raw[,unique(CAR.align)],
  function(x) compute_pairwise_mixed_effects(prolif_data_raw[t.type=='CD8'], x))
for (i in seq(length(models_cd8))) models_cd8[[i]]$t.type = 'CD8'

models_cd4 <- lapply(prolif_data_raw[,unique(CAR.align)],
  function(x) compute_pairwise_mixed_effects(prolif_data_raw[t.type=='CD4'], x))
for (i in seq(length(models_cd4))) models_cd4[[i]]$t.type = 'CD4'

models_combined <- lapply(prolif_data_raw[,unique(CAR.align)],
  function(x) compute_pairwise_mixed_effects(prolif_data_raw, x))
for (i in seq(length(models_combined))) models_combined[[i]]$t.type = 'both'

p_values <- data.table(t(sapply(
  c(models_cd8, models_cd4, models_combined),
    function(model_i) c(
      CAR.align=as.character(model_i$car),
      t.type=model_i$t.type,
      pval=as.numeric(anova(model_i$model)$`p-value`[2]),
      coef=as.numeric(model_i$model$coefficients[2])))))
p_values[, coef := as.numeric(coef)]
p_values[, pval := as.numeric(pval)]
p_values[, CAR.align := factor(CAR.align)]
p_values[, padj := p.adjust(as.numeric(pval), 'BH'), by='t.type']
```

