---
title: "fig1_complied.Rmd"
output:
  html_document:
    code_folding: hide
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, 
  output_dir = here::here('..','html'))})
---

```{r, message=FALSE, warning=FALSE}

library(data.table)
library(ggplot2)
library(knitr)
library(ggrepel)
library(RColorBrewer)
library(DESeq2)
library(plotly)
library(Rtsne)
library(scales)
library(dplyr)
library(grid)
library(ggridges)
library(ggtext)
library(patchwork)

setDTthreads(8)

data.output.dir <- file.path(here::here(
  '..','..',
  's3-roybal-tcsl',
  'lenti_screen_compiled_data','data'))

# set this to true to re-run, else will load from s3
rerun_deseq <- F
reload_data <- F

# arrayed list of CARs
array.list <- c('BAFF-R','TNR8','4-1BB','TACI','CD28','KLRG1','CD40')

# load colors
source(here::here('r','fig_colors.R'))

# map day 0 to both plus and minus
map_day_0 <- function(df) {
  return(rbind(
    df[k562!='none'],
    df[k562=='none'][, k562 := 'cd19+'],
    df[k562=='none'][, k562 := 'cd19-']
  ))
}

load(file=file.path(data.output.dir, 'pooled_deseq2_analysis_data.Rdata'))

```

## Load Exhaustion Data 
```{r}

data_dir <- here::here('..','data')

if (reload_data | !exists('exh_dt'))
  load(file.path(data_dir, 'exh.Rdata'))

exh_dt[, car := factor(car, levels=c(car_order,'untrans'))]

# some replicates appear to be incorrect - possibly due to evaporation or error in measurement.
# we will identify which wells are way off of the median value for the set of 3 replicates:
exh_means <- exh_dt[grep('_t',variable) & !is.na(donor), list(
  mean_val=mean(value, na.rm=T)),
  by=c('well','plate','day','variable','donor','row','col','k562','car','t_type')]

exh_means[, c('med_val','med_diff') := list(
  median(mean_val),
  (mean_val-median(mean_val))/median(mean_val)),
  by=c('day','car','k562','variable','donor','t_type')]

exh_means[, oob := abs(med_diff) >= 0.25]
exh_means[, n_oob := sum(oob), list(donor,k562,day,t_type,car,well,plate,variable)]

outlier_wells <- unique(exh_means[n_oob == 1, list(donor,k562,day,t_type,car,well,plate)])

exh_dt <- outlier_wells[, outlier_well := T][exh_dt, on=.(donor,k562,day,t_type,car,well,plate)]
exh_dt[is.na(outlier_well), outlier_well := F]

plots <- list()

cd4_marker_pos_threshold <- list(
  tim3_t= 666,
  gfp_t=1250,
  zombie_t=750,
  myc_t=1400,
  lag3_t= 950, 
  pd1_t= 1400,
  cd39_t= 1100)

cd8_marker_pos_threshold <- list(
  tim3_t= 666,
  gfp_t=1500,
  zombie_t=750,
  myc_t=1400,
  lag3_t= 800, 
  pd1_t= 1400,
  cd39_t= 1250)

censor_negative_min = -1500
```

### Supp 1: 28, BB, Zeta exhaustion data

```{r}

get_marker_counts <- function(exh_dt, exh_vars=c('tim3_t','lag3_t', 'pd1_t','cd39_t')) {
  marker_ct <- exh_dt[!outlier_well & variable %in% exh_vars,
    list(n_pos_marker= sum(gt_thresh)),
    by=c('well','plate','day','Time','car','donor','k562','t_type')]
  
  marker_ct <- marker_ct[, N := .N, by=c('well','plate','day','car','k562','t_type')][N > 1]
  
  marker_ct <- map_day_0(marker_ct)
  
  marker_freq <- marker_ct[, data.frame(table(factor(n_pos_marker, levels= 0:length(exh_vars)))), 
    by=c('well','plate','day','car','donor','k562','t_type')]
  names(marker_freq)[names(marker_freq) == 'Var1'] <- 'n_pos_marker'
  
  marker_freq[ n_pos_marker != 7, pct := Freq/sum(Freq), 
    by=c('well','plate','day','car','donor','k562','t_type')]
  
  return(marker_freq)
}

if (!exists('day_dt'))
  day_dt <- get_marker_counts(
    exh_dt,
    exh_vars=c('tim3_t','lag3_t', 'pd1_t','cd39_t'))[
      day %in% c(0,6,15,24,33) &
      car %in% c('CD28','41BB','zeta','untrans') &
      k562 == 'cd19+']

stacked_exh_plot <- function(day_dt_subset) {
  
  day_dt_subset <- day_dt_subset[, 
      c('mean_pct','sd_pct') := list(mean(pct), sd(pct)), 
      by=c('n_pos_marker','t_type','donor','day','k562','car')][,
        t_type := toupper(t_type)]
  
  day_dt_subset[, car := factor(car)]
  day_dt_subset[, pct := as.numeric(pct)]
  
  ggplot(unique(day_dt_subset[, list(car, mean_pct, n_pos_marker, day, t_type, donor)])) +
    geom_bar(aes(x=factor(day, levels=rev(levels(factor(day)))), y=mean_pct, fill=n_pos_marker),
      stat='identity', width=1, color='black', size=0.2) +
    facet_grid(car ~ donor, scales='free') +
    scale_y_continuous(expand=c(0,0), labels=label_percent()) +
    scale_x_discrete(expand=c(0,0), limits=rev) +
    scale_fill_manual(
      'Exh. Markers per cell', values=brewer.pal(9,'RdPu')[c(1,2,5,7,9)]) +
    labs(x="Days in Culture", y='Fraction of Cells') +
    theme_minimal() +
    theme(
      panel.grid=element_blank(),
      panel.border=element_rect(color='black', size=0.2, fill=NA))

}

plots$exh_stacked_bars <- ((
  stacked_exh_plot(day_dt[t_type == 'cd4' & day %in% c(0,15,24,33)][,
      donor := factor(paste0('Donor ',donor))]) +
    labs(subtitle='CD4', tag='B') +
    theme(
      panel.background = element_rect(fill='grey70'),
      legend.position='bottom',
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title=element_blank())
  ) / (
  stacked_exh_plot(day_dt[t_type == 'cd8' & day %in% c(0,15,24,33)][,
      donor := factor(paste0('Donor ',donor))]) +
    labs(subtitle='CD8', x='Day') +
    theme(
      panel.background = element_rect(fill='grey70'),
      legend.position='bottom',
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title.y=element_blank())
  )) + 
  plot_layout(guides='collect')

indiv_marker_means <- map_day_0(exh_dt)[(
    variable %in% c('tim3_t','lag3_t', 'pd1_t','cd39_t') &
    outlier_well==F &
    k562 == 'cd19+' &
    car %in% c('CD28','41BB','untrans','zeta')
  ),
  list(
    mean_val=mean(value),
    sem_val=sqrt(var(value)/.N)),
  by=.(donor, k562, day, t_type, car, variable)]

indiv_marker_means[, variable := factor(variable)]
indiv_marker_means[, variable := factor(variable,
  labels=toupper(gsub('_t','',levels(variable))))]

plot_indiv_marker_t_type <- function(indiv_marker_mean_subset) {
  ggplot(indiv_marker_mean_subset, 
       aes(x=day, color=car, y=mean_val)) + 
  geom_line() +
  geom_linerange(
    aes(
      ymin=mean_val-sem_val/2,
      ymax=mean_val+sem_val/2,
      group=interaction(car, day, variable, donor))) +
  geom_point() +
  scale_color_manual(values=c(car_colors, untrans='grey50')) +
  facet_grid(variable ~ donor, scale='free_y') +
  theme_minimal() +
  theme(
    panel.border = element_rect(fill=NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position='bottom',
    strip.background = element_blank())
}



plots$marker_means <- (
  plot_indiv_marker_t_type(indiv_marker_means[t_type == 'cd4'][, 
      donor := factor(paste0('Donor ',donor))][,
      variable := factor(variable, labels=levels(variable))]) +
    labs(subtitle='CD4', tag='A') +
    theme(
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title=element_blank())
  ) / (
  plot_indiv_marker_t_type(indiv_marker_means[t_type == 'cd8'][, 
      donor := factor(paste0('Donor ',donor))]) +
    labs(subtitle='CD8', x='Day') +
    theme(
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title.y=element_blank())
  ) + 
  plot_layout(guides='collect')

supp_S1_1 <- (
  plots$marker_means &
    guides(color=guide_legend(name='CAR',
      direction = "horizontal",
      title.position = "top",
      label.position = "bottom")) &
    theme(legend.position = 'bottom')) | 
  (plots$exh_stacked_bars &
    guides(fill=guide_legend(name='CAR',
      direction = "horizontal",
      title.position = "top",
      label.position = "bottom",
      keywidth=unit(1, 'lines'),
      keyheight=unit(1, 'lines'))) &
    theme(legend.position = 'bottom'))
```

### Sprinter vs Marathoner Comparison

```{r}
# calculate rel prev

read.counts[, car.abund.log := log10(car.abund)]

#assay_rep_list:
assay_rep_set <- unique(read.counts[
  data.table(
    assay=c('baseline','CTV1','CTV2','CTV3'), 
    prev_assay=c(NA,'baseline','CTV1','CTV2')), on='assay'][, 
  list(assay, sort.group, prev_assay, donor, batch, t.type, k.type)])

#map day0 
assay_rep_set <- rbind(
  assay_rep_set[assay=='baseline'][, k.type := 'pos'], 
  assay_rep_set[assay=='baseline'][, k.type := 'neg'], 
  assay_rep_set[assay!='baseline'])

#merge with prev copy to get prev sort.group correspondence
assay_rep_set <- assay_rep_set[, list(
    donor, batch, t.type, k.type,
    prev_assay=assay,prev.sort.group=sort.group)][
  assay_rep_set,
  on=c('donor','batch','t.type','k.type','prev_assay')]

# use baseline from prolif2 always
assay_rep_set[assay == 'CTV1', 
  prev.sort.group := gsub('prolif1','prolif2',prev.sort.group)]

#merge with prev measurements
prev_measure <- unique(read.counts[, list(
  car.abund.prev=car.abund, prev.sort.group=sort.group, CAR.align)])[
    assay_rep_set, on=c('prev.sort.group')]

#merge with orig read counts
read.counts <- prev_measure[, list(
    car.abund.prev, prev.sort.group, CAR.align, sort.group)][
      read.counts, on=c('sort.group','CAR.align')]

#calculate relative prev
read.counts[, car.abund.rel.prev := car.abund/car.abund.prev]

# expansion vs proliferation
car_label_set <- c('BAFF-R','CD30','4-1BB','TACI','CD28','KLRG1','CD40','NTB-A','CD2')
plot_set <- unique(
  read.counts[assay %in% c('CTV1', 'CTV2')][, 
    car.lbl := ifelse(CAR.align %in% car_label_set, as.character(CAR.align), '')][,
    list(car.lbl, rlog_car_score, car.abund.rel.baseline, car.abund.rel.prev, k.type, assay,
         t.type, donor, CAR.align, batch, sort.group, avg.divisions)])

early_v_late_indiv_dt <- dcast(
    plot_set, car.lbl+k.type+t.type + donor + CAR.align + batch ~ assay, 
    value.var=c('rlog_car_score','car.abund.rel.baseline','car.abund.rel.prev'))[
      k.type=='pos'][, late_v_early := log2(
        car.abund.rel.prev_CTV1/car.abund.rel.prev_CTV2)]

# early vs late stats
early_v_late_lm_dt <- early_v_late_indiv_dt[,
  data.table(
    summary(lm(late_v_early ~ 0+CAR.align))$coeff, keep.rownames=T),
    by='t.type']
setnames(early_v_late_lm_dt, c('rn','Pr(>|t|)'),c('CAR.align','p.val'))
early_v_late_lm_dt[, CAR.align := gsub('CAR.align','',CAR.align)]

# total exp stats
total_exp_lm_dt <- early_v_late_indiv_dt[,
  data.table(
    summary(lm(log2(car.abund.rel.baseline_CTV2) ~ 0+CAR.align))$coeff, keep.rownames=T),
    by='t.type']
setnames(total_exp_lm_dt,c('rn','Pr(>|t|)'),c('CAR.align','p.val'))
total_exp_lm_dt[, CAR.align := gsub('CAR.align','',CAR.align)]

sprinter_dt <- merge(
  total_exp_lm_dt,
  early_v_late_lm_dt,
  by=c('t.type', 'CAR.align'),
  suffixes=c(".total",".evl"))

sprinter_plot <- ggplot(
  sprinter_dt[,
    car.lbl := ifelse((p.val.total < 0.05 & Estimate.total > 0) | 
    (CAR.align %in% c('4-1BB','CD28','BAFF-R','TACI')), CAR.align, '')],
  aes(y=-Estimate.evl, x=Estimate.total, label=car.lbl)) + 
  geom_point(pch=21, aes(fill=Estimate.evl, size=ifelse(Estimate.total > 0, -log10(p.val.total),0))) +
  scale_fill_gradientn(colors=rev(hcl.colors(8,'PRGn')[2:7])) +
  facet_grid(t.type~., scales='free') +
  geom_text_repel(size=3, point.padding=0.25, segment.color='grey') +
  annotate(geom='label', x=-Inf, y=Inf, label='later/poor', 
    label.r=unit(0,'pt'), size=3, vjust=.99, hjust=.01, color=hcl.colors(8,'PRGn')[7]) +
  annotate(geom='label', x=-Inf, y=-Inf, label='earlier/poor', 
    label.r=unit(0,'pt'), size=3, vjust=.01, hjust=.01, color=hcl.colors(8,'PRGn')[2]) +
  annotate(geom='label', x=Inf, y=Inf, label='later/potent', 
    label.r=unit(0,'pt'), size=3, vjust=.99, hjust=.99, color=hcl.colors(8,'PRGn')[7]) +
  annotate(geom='label', x=Inf, y=-Inf, label='earlier/potent', 
    label.r=unit(0,'pt'), size=3, vjust=.01, hjust=.99, color=hcl.colors(8,'PRGn')[2]) +
  geom_vline(xintercept=0, linetype=2) +
  geom_hline(yintercept=0, linetype=2) +
  scale_size_continuous(range=c(1.5,5)) +
  scale_x_continuous(expand=c(0.2,0.1)) +
  scale_y_continuous(expand=c(0.3,0.1)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    panel.border = element_rect(colour = "black")) +
  labs(
    y='log2 Early:Late Relative Expansion',
    x='log2 Overall Relative Expansion, d0-14/16')
```

### Fig 1 Exh panel

```{r}
# donor 1 CD8 exh data for main text:
fig1_exh_panel <- stacked_exh_plot(day_dt[t_type == 'cd8' & day %in% c(0,15,24,33) & donor == 1][,
    donor := factor(paste0('Donor ',donor))]) +
  labs(x='Day') +
  scale_y_continuous(expand=c(0,0), labels=label_percent(), breaks=c(0,.5,1)) +
  guides(fill = guide_legend(
    title.position = "top", 
    title.hjust = 0.5,
    label.position = "bottom")) +
  theme(
    legend.position = 'top',
    strip.text.x = element_blank(),
    panel.spacing.y = unit(0.8, "lines"),
    panel.background = element_rect(fill='grey70'),
    legend.key.size = unit(0.8,'lines'),
    plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
    axis.title.y=element_blank())


ggsave(here::here('..','figs','compiled','fig1_exh.pdf'), fig1_exh_panel,
       height=4, width=1.5, useDingbats=FALSE)


```

### Main Fig 2

```{r}
plot_a <- plot_grid(
  barplot_stacked_plot_horiz+theme(legend.position = "none"), 
  (barplot_stacked_multi_plot / plot_spacer()) + plot_layout(heights=c(4.5,1)), 
  rel_widths=c(5,1),
  ncol = 2)

plot_b <- cytokine_panel + 
  guides(colour = guide_legend(reverse=T)) +
  theme(plot.margin = unit(c(0.5,1,1,0.8), "cm"), panel.grid=element_blank())

plot_c <- fig2_abundance_over_time_vert

plot_d <- sprinter_plot + theme(legend.position='none')

plot_e <- prolif_4v8_rel_vert

plot_f <- fig_2a_single_dendro

plot_abcde <- plot_grid(
  plot_a,
  plot_b,
  plot_grid(plot_c, plot_d, plot_e, labels=c('C','D','E'), ncol=3),
  plot_f,
  labels=c('A','B','','F'), ncol=1, nrow=4, rel_heights=c(0.9,0.9,1.2,1))

ggsave(here::here('..','figs','compiled','fig2.pdf'), plot_abcde,
       height=13, width=11, useDingbats=FALSE)
```

## Fig 2 Supps

### CD69 flowseq
```{r}

cd69.pct.pos <- dcast(
  read.counts[batch == "post-cytof" & assay == 'CD69'][
    bin %in% c('C','D'), list(pct_pos= sum(car.bin.pct)), 
      by=c('assay','CAR.align', 'k.type','t.type')],
  assay + CAR.align + t.type ~ k.type, value.var='pct_pos')

cd69.pct.pos[, CAR.align.assay := factor(paste(CAR.align,t.type,sep='|'))]
cd69.pct.pos[, CAR.align.assay := factor(
  CAR.align.assay, 
  levels=levels(CAR.align.assay),
  labels=cd69.pct.pos[, gsub('(.*)\\..*', '\\1', levels(CAR.align.assay))])]

cd69_panel <- ggplot(cd69.pct.pos) + 
  geom_segment(aes(x = reorder(CAR.align.assay, neg-pos), 
                   xend = reorder(CAR.align.assay, neg-pos), 
                   y = neg, 
                   yend = pos), color="grey") +
  geom_point(
    aes(x = reorder(CAR.align.assay, neg-pos), y = pos, color='CD19+'), 
    size=2.5) +
  geom_point(
    aes(x = reorder(CAR.align.assay, neg-pos), y = neg, color='CD19-'), 
    size=2.5) + 
  scale_color_manual(
      values=c('CD19+'=cd19_val[2], 'CD19-'='grey30')) + 
  facet_wrap(~ t.type, scales='free_x') +
  scale_y_continuous(label=percent) +
  scale_x_discrete(labels= remove_t_type_sep_col) +
  labs(y = 'CD69 % Positive') +
  theme_minimal() +
  theme(panel.border=element_rect(fill=NA),
        axis.text.x = element_markdown(angle = 90, hjust = 1, vjust=0.5, size=rel(0.8)),
        axis.title.x = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.background = element_rect(colour="white", fill="white"),
        legend.title = element_blank(),
        legend.justification=c(1,1),
        legend.position=c(0.99,1.01))

ggsave(here::here('..','figs','pooled','cd69_panel.pdf'), cd69_panel,
       height=3, width=8, useDingbats=FALSE)

supp_S2_2_cd69_panel <- cd69_panel
```
### Replicate Comparison

```{r}
assay_fig_labels <- c(
  'Initial\nProliferation\n(d0-d3/d4)', 
  'Relative\nExpansion\n(d0-d16)', 
  'Relative\nExpansion,\n(d0-d24)')


# combined rlog car score for CTV1 & CTV2, baseline abundance for CTV3
fig2_rep_comp <- rbind(
    plot_all_reps(
        df=read.counts[batch != 'post-cytof'], 
        value_col='rlog_car_score', df_only=T)[assay == 'CTV1'],
    plot_all_reps(
        df=read.counts[batch != 'post-cytof' & CAR.align != 'TNR8'], 
        value_col='car.abund.rel.baseline', df_only=T)[assay != 'CTV1'])

fig2_rep_comp[, assay := factor(assay, labels=assay_fig_labels)]

replicate_comp_plot <- ggplot(data=fig2_rep_comp, 
       aes(x_scaled_sep, y_scaled_sep)) + 
    geom_point(aes(color=interaction(rep_pair, k.type)), size=0.8) +
    scale_x_continuous(labels=scales::number_format(accuracy = .1), breaks=c(0,0.5,1)) +
    scale_y_continuous(labels=scales::number_format(accuracy = .1), breaks=c(0,0.5,1)) +
    theme_minimal() +
    coord_fixed() +
    theme(panel.border=element_rect(fill=NA), panel.grid=element_blank()) + 
    facet_grid(. ~t.type + assay) +
    scale_color_manual('', 
        values=brewer.pal(11,'PRGn')[c(2,3,4,10,9,8)],
        labels=c(
            'CD19-, A v B', 'CD19-, A v C', 'CD19-, B v C',
            'CD19+, A v B', 'CD19+, A v C', 'CD19+, B v C')) +
    labs(x='Scaled replicate 1', y='Scaled replicate 2')

supp_S2_1_replicate_comp_plot <- replicate_comp_plot

```

### Volcano Plot

```{r}
max_pval_y <- 6.5

#CD28 and 4-1BB Colors
receptor_cols <- RColorBrewer::brewer.pal(9, 'YlGnBu')[c(6,8)]

# label significant hits
data.dt[, CAR.type.size := CAR.type]
data.dt[CAR.type == 'other' & 
    ((padj < 0.05 & log2FoldChange > 0) | 
    (padj < 0.05 & log2FoldChange > 0)), 
  CAR.type.size := 'other_sig']

data.dt[, CAR.label.sig := '']
data.dt[CAR.type.size != 'other',
    CAR.label.sig := CAR.align]

# plot subset - CTV1, CTV2, and cumulative of all 3
data.subset.dt <- data.dt[
    k.type == 'pos' & 
        ((ref_set == 'baseline' & test_set == 'A' & assay != 'CTV1') | 
        (ref_set == 'CD' & test_set == 'A' & assay == 'CTV1'))]

# rename facets
data.subset.dt[, assay := factor(assay, labels=assay_fig_labels)]

# max out at log10-15
data.subset.dt[, padj.disp := -log10(padj)]
data.subset.dt[, CAR.pvalmax := padj.disp > max_pval_y]
data.subset.dt[padj.disp > max_pval_y, padj.disp := max_pval_y-0.18]

data.subset.dt[, order := ifelse(CAR.type=="other", 2, 1)]

interbin_volcano <- ggplot(data.subset.dt[order(CAR.type)], 
  aes(
    x=log2FoldChange, y=padj.disp,
    color=CAR.type.size,
    fill=CAR.type.size,
    label=CAR.label.sig,
    size=CAR.type.size,
    shape=CAR.pvalmax)) + 
  geom_point() + 
  facet_grid(t.type ~ assay) +
  scale_color_manual('',
    labels=c('New Receptors', '4-1BB', 'CD28', 'New Receptors'),
    values=c('grey50', receptor_cols, outlier_cols[2]),
    guide=F) +
  scale_fill_manual('',
    labels=c('New Receptors', '4-1BB', 'CD28', 'New Receptors'),
    values=c('grey50', receptor_cols, outlier_cols[2]),
    guide=F) +
  scale_shape_manual(values=c(21,24), guide=F) +
  scale_size_manual('',
    labels=c('New Receptors', '4-1BB', 'CD28', 'New Receptors'),
    values=c(1.5,3,3,2.5), guide=F) +
  geom_hline(yintercept=-log10(0.05), linetype = 'dashed', alpha=.3) +
  labs(x='Relative Proliferation/Expansion,\nlog2 FC', 
       y='-log10(p)') + 
  scale_y_continuous(limits=c(0, max_pval_y), expand=c(.05,.05,0,0)) +
  scale_x_continuous(limits=c(-3.25,3.25), breaks=c(-3:3)) +
  geom_text_repel(size=3, point.padding=0.25, text.padding=0.25, segment.color='grey', max.overlaps=Inf) +
  theme_minimal() +
  theme(panel.border=element_rect(fill=NA), panel.grid=element_blank())

supp_S2_5_interbin_volcano <- interbin_volcano
```

### CD19 neg pos comparison
```{r}

pos_neg_comparisons <- read.counts[grepl('CTV', assay), {
  if (length(unique(sort.group)) == 2)
    cast_comparison(
      .SD,
      unique(sort.group[k.type == 'neg']),
      unique(sort.group[k.type == 'pos']))
  },
  by=c('donor','assay','batch','t.type')][assay == 'CTV1']

pos_neg_comparisons[, y_scaled_comb_rank := rank(y_scaled_comb), by='y.group']
pos_neg_comparisons[, x_scaled_comb_rank := rank(x_scaled_comb), by='x.group']

pos_neg_comparisons_melt <- melt(
  pos_neg_comparisons[, 
    xy_ratio := x_scaled_comb/y_scaled_comb], measure.vars= grep(
  '^[xy][^.]', names(pos_neg_comparisons), perl=T, value=T)
  )[, 
    `:=`(var_mean= mean(value, na.rm=T), var_sd= sd(value, na.rm=T)), 
    by=c('t.type','CAR.align','variable')]

cast_left <- paste(names(pos_neg_comparisons_melt)[1:6], collapse = ' + ')
cast_right <- 'variable'
cast_formula <- paste(cast_left, cast_right, sep= ' ~ ')

pos_neg_assay_avg <- dcast(
  pos_neg_comparisons_melt, cast_formula, value.var='var_mean')

pos_neg_assay_plot <- unique(
  pos_neg_assay_avg[, list(t.type, y_scaled_comb, x_scaled_comb, y_scaled_comb_rank, x_scaled_comb_rank, CAR.align)])
pos_neg_assay_plot[, label.few := '']
pos_neg_assay_plot[
  CAR.align %in% c('BAFF-R','CD30','4-1BB','TACI','CD28','KLRG1','CD40','NTB-A','CD2'),
  label.few := CAR.align]

# stats
pos_neg_stats <- rbind(
  data.table(
    test='spearman',
    t.type=c('CD4','CD8'),
    rbind(
      with(pos_neg_assay_plot[t.type=='CD4'],
        cor.test(y_scaled_comb_rank, x_scaled_comb_rank, method='spearman'))[
          c('estimate','p.value')],
      with(pos_neg_assay_plot[t.type=='CD8'],
        cor.test(y_scaled_comb_rank, x_scaled_comb_rank, method='spearman'))[
          c('estimate','p.value')])),
  unique(pos_neg_assay_plot[,
    cor.test(y_scaled_comb, x_scaled_comb, method='pearson'), by='t.type'][,
      list(t.type, estimate, p.value, test='pearson')])
)
pos_neg_stats$estimate <- unlist(pos_neg_stats$estimate)
pos_neg_stats$p.value <- unlist(pos_neg_stats$p.value)

fancy_scientific <- function(l) {
     # turn in to character string in scientific notation
     l <- format(l, scientific = TRUE)
     # quote the part before the exponent to keep all the digits
     l <- gsub("^(.*)e", "'\\1'e", l)
     # turn the 'e+' into plotmath format
     l <- gsub("e", "%*%10^", l)
     # return this as an expression
     parse(text=l)
}

# with axis cuts
ggplot_pos_neg_assay <- ggplot(pos_neg_assay_plot, 
       aes(x=x_scaled_comb, y=y_scaled_comb, label=label.few)) + 
    geom_point(color='grey30') + 
    facet_grid( ~ t.type, scale='free') + 
    scale_x_continuous(expand=expansion(mult=c(.1,.1), add=0), limits=c(0,NA)) +
    scale_y_continuous(limits=c(0.48, 0.985), expand=expansion(mult=c(.05,.05), add=0)) +
    geom_text_repel(size=2.25, max.overlaps=Inf) +
    geom_text(data=pos_neg_stats[test=='pearson'], 
      mapping=aes(label=paste0("r == ", round(estimate,2))), 
      position=position_nudge(x = 1),
      x=-Inf, y=Inf,
      size=2.8, vjust=1, hjust=0, parse=TRUE) +
    geom_text(data=pos_neg_stats[test=='pearson'], 
      mapping=aes(label=paste0("p == ", fancy_scientific(signif(p.value,2)))), 
      position=position_nudge(x = 1),
      x=-Inf, y=Inf,
      size=2.8, vjust=1.8, hjust=0, parse=TRUE) +
    labs(
        title='Scaled Mean Proliferation',
        subtitle='(means of scaled replicates)',
        y='CD19+ Proliferation', 
        x='CD19- Proliferation') +
    theme_minimal() +
    theme(
      panel.spacing.y=unit(1.5, "lines"),
      panel.border=element_rect(color='black', fill=NA),
      panel.grid=element_blank())

ggplot_pos_neg_assay_rank <- ggplot(pos_neg_assay_plot, 
       aes(x=x_scaled_comb_rank, y=y_scaled_comb_rank, label=label.few)) + 
    geom_point(color='grey30') + 
    facet_grid( ~ t.type, scale='free') + 
    geom_text_repel(size=2.25, max.overlaps=Inf) +
    geom_text(data=pos_neg_stats[test=='spearman'], 
      mapping=aes(label=paste0("rho == ", round(estimate,2))), 
      position=position_nudge(x = 1),
      x=-Inf, y=Inf,
      size=2.8, vjust=1, hjust=0, parse=TRUE) +
    geom_text(data=pos_neg_stats[test=='spearman'], 
      mapping=aes(label=paste0("p == ", fancy_scientific(signif(p.value,2)))), 
      position=position_nudge(x = 1),
      x=-Inf, y=Inf,
      size=2.8, vjust=1.8, hjust=0, parse=TRUE) +
    labs(
        title='Proliferation Rank',
        subtitle='(mean rank across replicates)',
        y='CD19+ mean rank', 
        x='CD19- mean rank') +
    theme_minimal() +
    theme(
      strip.text=element_blank(),
      panel.spacing.y=unit(1.5, "lines"),
      panel.border=element_rect(color='black', fill=NA),
      panel.grid=element_blank())

#supp_S2_4_pos_neg <- ggplot_pos_neg_assay
supp_S2_4_pos_neg <- (ggplot_pos_neg_assay | ggplot_pos_neg_assay_rank)

```


```{r}
### Assemble Supp Fig 1/2

supp_fig_1 <- (
  ((supp_S1_1 / plot_spacer()) + plot_layout(heights=c(1,0.01))) | 
  (
    (supp_S2_1_replicate_comp_plot + 
       guides(col = guide_legend(nrow = 2, byrow=T)) +
       theme(legend.position='bottom', legend.margin = margin(0,0,0,0,'lines'))) /
    supp_S2_2_cd69_panel /
    supp_S2_5_interbin_volcano /
    plot_spacer() /
    supp_S2_4_pos_neg) + 
      plot_layout(
        ncol=1, heights=c(.8,0.8,1.7,0.2,1))) +
  plot_layout(ncol=2, widths=c(0.4, 0.6))

fig_scaling <- 1.2
ggsave(here::here('..','figs','compiled','figS1.pdf'), supp_fig_1,
       height=13*fig_scaling, width=11*fig_scaling, useDingbats=FALSE)

```