---
title: "fig4_complied.Rmd"
output:
  html_document:
    code_folding: hide
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, 
  output_dir = here::here('..','html','pooled'))})
---

```{r, message=FALSE, warning=FALSE}
library(data.table)
library(ggplot2)
library(knitr)
library(ggrepel)
library(RColorBrewer)
library(DESeq2)
#library(rnaseqGene)
library(plotly)
library(Rtsne)
library(scales)
library(dplyr)
library(grid)
library(ggridges)
library(cowplot)
library(stringr)

#rm(list = ls())
setDTthreads(8)

# data.output.dir <- file.path(here::here(
#   '..','..',
#   's3-roybal-tcsl',
#   'lenti_screen_compiled_data','data'))

# get local path to s3 dir and other local settings
source(here::here('r','local_settings.R'))

# set this to true to re-run, else will load from s3
rerun_deseq <- F
reload_data <- F

# arrayed list of CARs
array.list <- c('BAFF-R','CD30','4-1BB','TACI','CD28','KLRG1','CD40')

# load colors
source(here::here('r','fig_colors.R'))

local.data.dir <- '/Volumes/HFSE/lenti-data'
if (reload_data | !exists('ctv_gated_means_dt'))
  load(file=file.path(local.data.dir, 'ctv_plot_data.Rdata'))

plots <- list()

```

## Load Exhaustion Data 
```{r}

if (reload_data | !exists('exh_dt'))
  load(file.path(local.data.dir, 'exh.sampled.Rdata'))
  #load(file.path(s3.data.dir, 'exh.Rdata'))

exh_dt[, car := factor(car, levels=c(car_order,'untrans'))]

# some replicates appear to be incorrect - possibly due to evaporation or error in measurement.
# we will identify which wells are way off of the median value for the set of 3 replicates:
exh_means <- exh_dt[grep('_t',variable) & !is.na(donor), list(
  mean_val=mean(value, na.rm=T)),
  by=c('well','plate','day','variable','donor','row','col','k562','car','t_type')]

exh_means[, c('med_val','med_diff') := list(
  median(mean_val),
  (mean_val-median(mean_val))/median(mean_val)),
  by=c('day','car','k562','variable','donor','t_type')]

exh_means[, oob := abs(med_diff) >= 0.25]
exh_means[, n_oob := sum(oob), list(donor,k562,day,t_type,car,well,plate,variable)]

outlier_wells <- unique(exh_means[n_oob == 1, list(donor,k562,day,t_type,car,well,plate)])

exh_dt <- outlier_wells[, outlier_well := T][exh_dt, on=.(donor,k562,day,t_type,car,well,plate)]
exh_dt[is.na(outlier_well), outlier_well := F]

plots <- list()

cd4_marker_pos_threshold <- list(
  tim3_t= 666,
  gfp_t=1250,
  zombie_t=750,
  myc_t=1400,
  lag3_t= 950, 
  pd1_t= 1400,
  cd39_t= 1100)

cd8_marker_pos_threshold <- list(
  tim3_t= 666,
  gfp_t=1500,
  zombie_t=750,
  myc_t=1400,
  lag3_t= 800, 
  pd1_t= 1400,
  cd39_t= 1250)

censor_negative_min = -1500
```

## CTV

### CTV Traces

```{r}
  
ctv_gated_means_subset <- ctv_gated_means_dt[variable=='ctv2_t' & k562 == 'cd19+']

ctv_gated_means_donormerge_dt <- ctv_gated_means_subset[
  # leave out donor 1 day 33 in cd8s?
  #(donor %in% c(1,2) & day != 'd33') | ((donor == 2 & day == 'd33') | t_type == 'cd4'),
  ,
  `:=`(
  value_rel_day_mean= mean(value_rel_day, na.rm=T),
  value_rel_day_sd= sd(value_rel_day)),
  by=c('k562','day','car','variable','t_type')]

ctv_gated_means_donormerge_subset <- ctv_gated_means_donormerge_dt[
  variable %in% c('ctv2_t') & k562 == 'cd19+']

max_val <- ctv_gated_means_donormerge_subset[, max(abs(value_rel_day_mean[car != 'KLRG1']), na.rm=T)]

ctv_gated_means_donormerge_subset[
  abs(value_rel_day_mean) > max_val,
  value_rel_day_mean := max_val * sign(value_rel_day_mean)]

ctv_gated_means_donormerge_subset[, t_type := factor(t_type, labels=c('CD4','CD8'))]

proliferation_tiles <- ggplot(ctv_gated_means_donormerge_subset,
    aes(fill=0-value_rel_day_mean, y=factor(car, levels=rev(car_order)), x=day)) + 
  geom_tile(color='white') + 
  facet_grid(. ~ t_type) + 
  scale_fill_viridis_c(
    'Relative Proliferation (-ΔMFI)\n(mean of 2 donors)',
    limits = c(-1,1)*max_val, oob=scales::squish,
    breaks=c(300, 150, 0, -150, -300),
    labels=c(300,150,0,-150, '≤-300'),
    na.value = '#FFFFFF') + 
  theme_minimal(base_size=12) + 
  theme(
    panel.background=element_rect(fill="white", colour="white"),
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    legend.position = "bottom") +
  scale_y_discrete('', expand=c(0,0)) + 
  scale_x_discrete('', expand=c(0,0))

proliferation_tiles
```

### CTV cd19- tiles, supp

```{r}
  
ctv_gated_means_subset_supp <- ctv_gated_means_dt[variable=='ctv2_t' & k562 == 'cd19-']

ctv_gated_means_donormerge_supp_dt <- ctv_gated_means_subset_supp[
  # leave out donor 1 day 33 in cd8s?
  #(donor %in% c(1,2) & day != 'd33') | ((donor == 2 & day == 'd33') | t_type == 'cd4'),
  ,
  `:=`(
  value_rel_day_mean= mean(value_rel_day, na.rm=T),
  value_rel_day_sd= sd(value_rel_day)),
  by=c('k562','day','car','variable','t_type')]

ctv_gated_means_donormerge_supp_subset <- ctv_gated_means_donormerge_supp_dt[
  variable %in% c('ctv2_t') & k562 == 'cd19-']

max_val <- ctv_gated_means_donormerge_supp_subset[, max(abs(value_rel_day_mean[car != 'KLRG1']), na.rm=T)]

ctv_gated_means_donormerge_supp_subset[
  abs(value_rel_day_mean) > max_val,
  value_rel_day_mean := max_val * sign(value_rel_day_mean)]

ctv_gated_means_donormerge_supp_subset[, t_type := factor(t_type, labels=c('CD4','CD8'))]

proliferation_tiles_neg <- ggplot(ctv_gated_means_donormerge_supp_subset,
    aes(fill=0-value_rel_day_mean, y=factor(car, levels=rev(car_order)), x=day)) + 
  geom_tile(color='white') + 
  facet_grid(. ~ t_type) + 
  scale_fill_viridis_c(
    'Relative Proliferation (-ΔMFI)\n(mean of 2 donors)',
    limits = c(-1,1)*max_val, oob=scales::squish,
    breaks=c(300, 150, 0, -150, -300),
    labels=c(300,150,0,-150, '≤-300'),
    na.value = '#FFFFFF') + 
  theme_minimal(base_size=12) + 
  theme(
    panel.background=element_rect(fill="white", colour="white"),
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    legend.position = "bottom") +
  scale_y_discrete('', expand=c(0,0)) + 
  scale_x_discrete('', expand=c(0,0))

proliferation_tiles_neg
```

```{r}
make_ridge_plot_panel <- function(df, var, show_line=F, facet_formula=' ~ t_type + day') {
  
  df[, car := factor(car, levels=car_order)]
  
  df_ct <- df[, .N, by=c(c('day','car','donor','k562'))]
  
  var_disp = toupper(gsub('(.*)_t','\\1',var))
  
  p <- ggplot(df[variable == var & value < 3200]) + 
  geom_density_ridges(
    aes(y=factor(car, levels=rev(car_order)), x=value, color=car, fill=car, height=..ndensity..), 
    alpha=0.7, scale=1) +
  facet_grid(as.formula(facet_formula), switch="both") +
  xlim(c(600, NA)) +
  theme_minimal() +
  scale_fill_manual(values=rev(car_colors)) +
  scale_y_discrete(expand=c(0.05,0.01)) +
  scale_color_manual(values=rev(car_colors))
  
  if (show_line) {
    p <- p + geom_vline(xintercept=df[[var]])
  }
       
  return(p)
}

ctv_2_days <- make_ridge_plot_panel(
  ctv_fig_subset_dt[k562=='cd19+' & donor == 2 & (
      (t_type == 'cd8' & day %in% c('d3', 'd33'))
      | (t_type == 'cd4' & day %in% c('d14', 'd33')))], 'ctv2_t') +
    labs(x='CTV (AU) (Donor 2)', y= '') + 
  theme(
    legend.position='none',
    panel.border=element_rect(color='black', fill=NA),
    axis.text.x = element_blank())

ctv_2_days

traces_right <- plot_grid(proliferation_tiles, ctv_2_days, align = "h", axis = "bt", rel_widths = c(1.6, 1))

traces_horiz <- (
  (proliferation_tiles+
    theme(legend.position = "top", legend.title=element_text(size=rel(0.8))) +
    guides(fill = guide_colorbar(title.position = "top", title.hjust = 0, barwidth=10))) /
  ctv_2_days) & theme(plot.margin=margin(0,0,0,-10,'pt'), panel.grid=element_blank())

plots$ctv_supp <- make_ridge_plot_panel(
    ctv_fig_subset_dt[k562=='cd19+' & t_type == 'cd4' & donor == 1],
    'ctv2_t', facet_formula='~ day') +
      labs(title='CD4', x='CTV (AU) (Donor 1)', y= '') + 
    theme(
      legend.position='none',
      panel.border=element_rect(color='black', fill=NA),
      axis.text.x = element_blank()) | 
  make_ridge_plot_panel(
    ctv_fig_subset_dt[k562=='cd19+' & t_type == 'cd4' & donor == 2],
    'ctv2_t', facet_formula='~ day') +
      labs(x='CTV (AU) (Donor 2)', y= '') + 
    theme(
      legend.position='none',
      axis.text.y = element_blank(),
      panel.border=element_rect(color='black', fill=NA),
      axis.text.x = element_blank()) | 
  make_ridge_plot_panel(
    ctv_fig_subset_dt[k562=='cd19+' & t_type == 'cd8' & donor == 1],
    'ctv2_t', facet_formula='~ day') +
      labs(title='CD8', x='CTV (AU) (Donor 1)', y= '') + 
    theme(
      legend.position='none',
      panel.border=element_rect(color='black', fill=NA),
      axis.text.x = element_blank()) | 
  make_ridge_plot_panel(
    ctv_fig_subset_dt[k562=='cd19+' & t_type == 'cd8' & donor == 2],
    'ctv2_t', facet_formula='~ day') +
      labs(x='CTV (AU) (Donor 2)', y= '') + 
    theme(
      legend.position='none',
      axis.text.y = element_blank(),
      panel.border=element_rect(color='black', fill=NA),
      axis.text.x = element_blank())

plots$ctv_cd19neg_supp <- (
  make_ridge_plot_panel(
    ctv_fig_subset_dt[k562=='cd19-' & t_type == 'cd4' & donor == 1],
    'ctv2_t', facet_formula='~ day') +
      labs(title='CD4', x='', y= '') + 
    theme(
      legend.position='none',
      axis.title.x = element_blank(),
      panel.border=element_rect(color='black', fill=NA),
      axis.text.x = element_blank()) | 
  make_ridge_plot_panel(
    ctv_fig_subset_dt[k562=='cd19-' & t_type == 'cd4' & donor == 2],
    'ctv2_t', facet_formula='~ day') +
      labs(x='', y= '') + 
    theme(
      legend.position='none',
      axis.title.x = element_blank(),
      axis.text.y = element_blank(),
      panel.border=element_rect(color='black', fill=NA),
      axis.text.x = element_blank())
) / (
  make_ridge_plot_panel(
    ctv_fig_subset_dt[k562=='cd19-' & t_type == 'cd8' & donor == 1],
    'ctv2_t', facet_formula='~ day') +
      labs(title='CD8', x='CTV (AU) (Donor 1)', y= '') + 
    theme(
      legend.position='none',
      panel.border=element_rect(color='black', fill=NA),
      axis.text.x = element_blank()) | 
  make_ridge_plot_panel(
    ctv_fig_subset_dt[k562=='cd19-' & t_type == 'cd8' & donor == 2],
    'ctv2_t', facet_formula='~ day') +
      labs(x='CTV (AU) (Donor 2)', y= '') + 
    theme(
      legend.position='none',
      axis.text.y = element_blank(),
      panel.border=element_rect(color='black', fill=NA),
      axis.text.x = element_blank()))


```

## CD4 CD40 Cumulative Growth
```{r}

cd4_cumulative_growth <- fread(file.path(
  s3.data.dir, 'csv/cd4_cumulative_growth.csv'))
setnames(cd4_cumulative_growth, 'TNR8','CD30')
car_expansion <- melt(cd4_cumulative_growth, measure.vars=c('41BB','BAFF-R','CD28','CD40','KLRG1','TACI','CD30','zeta'))

cd4_expansion_plot <- ggplot(car_expansion[
        measure=='expansion' & variable %in% c('CD40','CD28','41BB')],
    aes(x=V1, y=value, color=variable, shape=factor(donor))) +
  geom_line(size=1) +
  geom_point(size=3) +
  scale_color_manual('Domain', values =car_colors) +
  scale_shape_discrete('Donor') +
  theme_bw() +
  labs(
    x='Days in culture',
    y='Cumulative Fold Expansion',
    title='Cumulative CD4 T cell Expansion in culture')

# exponential fit linear model
summary(lm(formula=doublings~V1*variable+donor,
  data=car_expansion[
    measure=='expansion' &
    variable %in% c('CD40','CD28','41BB')][
      value > 0, doublings := log(value, base=2)]))

# exponential fit, repeated measures anova
exp_model <- aov(formula=doublings~V1*variable + Error(donor),
  data=car_expansion[
    measure=='expansion' &
    variable %in% c('CD40','CD28','41BB')][
      value > 0, doublings := log(value, base=2)][,
        variable := relevel(variable, 'CD28')])

# Performed a repeated measures ANOVA
# p CD28 to CD40: .00113
# p 41BB to CD40: 4.5e-11


```
## Exhaustion Plots

### PD1
```{r}
pd1_line_plot <- ggplot(
    map_day_0(exh_dt[outlier_well==F])[
      variable=='pd1_t' & k562 == 'cd19+' & day < 33 & car %in% c('BAFF-R','CD28','41BB','TACI') & 
        value > censor_negative_min][,
            list(pct= sum(gt_thresh)/.N),
          by=.(car, day, donor, variable, t_type)][,
            list(mean_pct=mean(pct), sd_pct=sd(pct)), 
          by=.(car, day,variable, t_type)][, t_type := factor(t_type, labels=c('CD4','CD8'))], 
    aes(x=day, y=mean_pct, ymin=mean_pct-sd_pct/sqrt(2), ymax=mean_pct+sd_pct/sqrt(2), color=car, group=car)) + 
    facet_grid(t_type~., scales='free_y') +
    geom_line() +
    geom_point() + 
    geom_linerange() +
    scale_x_continuous(breaks=c(0,6,15,24,33)) + 
    scale_y_continuous(labels=scales::percent) +
    scale_color_manual(values=c(car_colors, untrans='grey80', zeta='black'), ) +
    theme_minimal() + 
    labs(y='% PD1+', x='Days in culture') +
    theme(
        panel.border = element_rect(fill=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank())

pd1_line_plot_v2 <- ggplot(
    map_day_0(exh_dt[outlier_well==F])[
      variable=='pd1_t' & k562 == 'cd19+' & day < 33 & car %in% c('BAFF-R','CD28','41BB','TACI') & 
        value > censor_negative_min][,
            list(pct= sum(gt_thresh)/.N),
          by=.(car, day, donor, variable, t_type)][,
            list(mean_pct=mean(pct), sd_pct=sd(pct)), 
          by=.(car, day,donor, variable, t_type)][, t_type := factor(t_type, labels=c('CD4','CD8'))], 
    aes(x=day, y=mean_pct, ymin=mean_pct-sd_pct/sqrt(2), ymax=mean_pct+sd_pct/sqrt(2), color=car, group=car)) + 
    facet_grid(donor~t_type, scales='free_y') +
    geom_line() +
    geom_point() + 
    geom_linerange() +
    scale_x_continuous(breaks=c(0,6,15,24,33)) + 
    scale_y_continuous(labels=scales::percent) +
    scale_color_manual(values=c(car_colors, untrans='grey80', zeta='black'), ) +
    theme_minimal() + 
    labs(y='% PD1+', x='Days in culture') +
    theme(
        legend.position='none',
        panel.border = element_rect(fill=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank())

#pd1_line_plot

#pd1_line_plot_v2
```
### Stacked Exhaustion Bars

```{r}
# stacked plot
# day_dt[,
#   list(n_pos_marker=as.numeric(rep(n_pos_marker, Freq))),
#   by=.(day, car, t_type, donor, well)][
#     day== 6,
#     summary(glm(
#       n_pos_marker ~ car + donor + 0,
#       family=poisson))]

get_marker_counts <- function(exh_dt, exh_vars=c('tim3_t','lag3_t', 'pd1_t','cd39_t')) {
  marker_ct <- exh_dt[!outlier_well & variable %in% exh_vars,
    list(n_pos_marker= sum(gt_thresh)),
    by=c('well','plate','day','Time','car','donor','k562','t_type')]
  
  marker_ct <- marker_ct[, N := .N, by=c('well','plate','day','car','k562','t_type')][N > 1]
  
  marker_ct <- map_day_0(marker_ct)
  
  marker_freq <- marker_ct[, data.frame(table(factor(n_pos_marker, levels= 0:length(exh_vars)))), 
    by=c('well','plate','day','car','donor','k562','t_type')]
  names(marker_freq)[names(marker_freq) == 'Var1'] <- 'n_pos_marker'
  
  marker_freq[ n_pos_marker != 7, pct := Freq/sum(Freq), 
    by=c('well','plate','day','car','donor','k562','t_type')]
  
  return(marker_freq)
}

if (!exists('day_dt'))
  day_dt <- get_marker_counts(
    exh_dt,
    exh_vars=c('tim3_t','lag3_t', 'pd1_t'))[
      day %in% c(6,15) &
      car %in% c('41BB','CD28','BAFF-R') &
      k562 == 'cd19+']

stacked_exh_plot <- function(day_dt_subset) {
  
  day_dt_subset <- day_dt_subset[, 
      c('mean_pct','sd_pct') := list(mean(pct), sd(pct)), 
      by=c('n_pos_marker','t_type','donor','day','k562','car')][,
        t_type := toupper(t_type)]
  
  day_dt_subset[, car := factor(car)]
  day_dt_subset[, pct := as.numeric(pct)]
  
  ggplot(unique(day_dt_subset[, list(car, mean_pct, n_pos_marker, day, t_type, donor)])) +
    geom_bar(aes(x=car, y=mean_pct, fill=n_pos_marker),
      stat='identity', width=1, color='black', size=0.2) +
    facet_grid(day ~ donor, scales='free') +
    scale_y_continuous(expand=c(0,0), labels=label_percent()) +
    scale_x_discrete(expand=c(0,0), limits=rev) +
    scale_fill_manual(
      'Exh. Markers\n per cell', values=brewer.pal(9,'RdPu')[c(1,2,5,8)]) +
    labs(x="CAR", y='Fraction of Cells') +
    theme_minimal() +
    coord_flip() +
    theme(
      panel.grid=element_blank(),
      panel.border=element_rect(color='black', size=0.2, fill=NA))
}

plots$exh_stacked_bars <- (
  stacked_exh_plot(day_dt[t_type == 'cd4'][, day := factor(day, labels=paste0('d',c(6,15)))][,
      donor := factor(paste0('Donor ',donor))]) +
    labs(subtitle='CD4') +
    theme(
      axis.text.x=element_blank(),
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.text.y=element_text(color=car_colors[rev(c('CD28','41BB','BAFF-R'))], face='bold', size=rel(1.1)),
      axis.title=element_blank())
  ) / (
  stacked_exh_plot(day_dt[t_type == 'cd8'][, day := factor(day, labels=paste0('d',c(6,15)))][,
      donor := factor(paste0('Donor ',donor))]) + 
    labs(subtitle='CD8') +
    theme(
      strip.text.x=element_text(size=0),
      plot.margin=margin(0,5.5,5.5,5.5,'pt'),
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.text.y=element_text(color=car_colors[rev(c('CD28','41BB','BAFF-R'))], face='bold', size=rel(1.1)),
      axis.title=element_blank())
  ) + 
  plot_layout(guides='collect')

plots$exh_stacked_bars

```
### Stacked Exh Bars with TACI

```{r}


if (!exists('day_dt') | !('TACI' %in% day_dt$car))
  day_dt <- get_marker_counts(
    exh_dt,
    exh_vars=c('tim3_t','lag3_t', 'pd1_t'))[
      day %in% c(6,15) &
      car %in% c('41BB','CD28','BAFF-R', 'TACI') &
      k562 == 'cd19+']

stacked_exh_plot <- function(day_dt_subset) {
  
  day_dt_subset <- day_dt_subset[, 
      c('mean_pct','sd_pct') := list(mean(pct), sd(pct)), 
      by=c('n_pos_marker','t_type','donor','day','k562','car')][,
        t_type := toupper(t_type)]
  
  day_dt_subset[, car := factor(car)]
  day_dt_subset[, pct := as.numeric(pct)]
  
  ggplot(unique(day_dt_subset[, list(car, mean_pct, n_pos_marker, day, t_type, donor)])) +
    geom_bar(aes(x=car, y=mean_pct, fill=n_pos_marker),
      stat='identity', width=1, color='black', size=0.2) +
    facet_grid(day ~ donor, scales='free') +
    scale_y_continuous(expand=c(0,0), labels=label_percent()) +
    scale_x_discrete(expand=c(0,0), limits=rev) +
    scale_fill_manual(
      'Exh. Markers\n per cell', values=brewer.pal(9,'RdPu')[c(1,2,5,8)]) +
    labs(x="CAR", y='Fraction of Cells') +
    theme_minimal() +
    coord_flip() +
    theme(
      panel.grid=element_blank(),
      panel.border=element_rect(color='black', size=0.2, fill=NA))
}

plots$exh_stacked_bars_taci <- (
  stacked_exh_plot(day_dt[t_type == 'cd4'][, day := factor(day, labels=paste0('d',c(6,15)))][,
      donor := factor(paste0('Donor ',donor))]) +
    labs(subtitle='CD4') +
    theme(
      axis.text.x=element_blank(),
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.text.y=element_text(color=car_colors[rev(c('CD28','41BB','BAFF-R','TACI'))], face='bold', size=rel(1.1)),
      axis.title=element_blank())
  ) / (
  stacked_exh_plot(day_dt[t_type == 'cd8'][, day := factor(day, labels=paste0('d',c(6,15)))][,
      donor := factor(paste0('Donor ',donor))]) + 
    labs(subtitle='CD8') +
    theme(
      strip.text.x=element_text(size=0),
      plot.margin=margin(0,5.5,5.5,5.5,'pt'),
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.text.y=element_text(color=car_colors[rev(c('CD28','41BB','BAFF-R','TACI'))], face='bold', size=rel(1.1)),
      axis.title=element_blank())
  ) + 
  plot_layout(guides='collect')

plots$exh_stacked_bars_taci

```


### Exhaustion stats

```{r}
exh_stat_dt <- get_marker_counts(
    exh_dt,
    exh_vars=c('tim3_t','lag3_t', 'pd1_t'))[
      k562 == 'cd19+'][,
      donor := factor(paste0('Donor ',donor))][, 
        list(
          mean.markers= sum(as.numeric(n_pos_marker) * pct)/sum(pct),
          pct.sum =sum(pct)),
        by=.(plate, day, car, donor, k562, t_type)][,
        day := factor(day, ordered=T)]


ggplot(exh_stat_dt,
  aes(x=day, y=mean.markers, 
      color=car, group=interaction(car, donor, t_type))) + 
  geom_line() +
  geom_point() + 
  facet_wrap(donor ~ t_type) +
  scale_color_manual(values=car_colors)

aov_formula <- mean.markers~day*car + Error(donor+t_type)

overall_model <- aov(
  formula=aov_formula,
  data=exh_stat_dt)

post_hoc_pval <- function(car_pair) {
  model <- aov(
    formula=aov_formula, 
    data=exh_stat_dt[car %in% car_pair])
  aov_df <- data.table(summary(model)$`Error: Within`[[1]], keep.rownames = T)
  
  aov_df[, car_a := car_pair[1]]
  aov_df[, car_b := car_pair[2]]
  
  return(aov_df)
}

#cars ordered by mean exhaustion rank
cars_exh_order <- as.character(
  exh_stat_dt[, 
    list(car, rank=rank(mean.markers)), by=.(donor,day,t_type)][,
      list(mean.rank= mean(rank)), by='car'][order(mean.rank), car])

all_pairs <- rbindlist(
  apply(combn(cars_exh_order, 2), 2, post_hoc_pval))
all_pairs[, p.adj := p.adjust(`Pr(>F)`, method='BH'), by=rn]
all_pairs[, car_a := factor(car_a, levels=cars_exh_order)]
all_pairs[, car_b := factor(car_b, levels=cars_exh_order)]
all_pairs[, rn := str_trim(rn)]
all_pairs <- add_significance(all_pairs, p.col='p.adj')

# showing both car and car:day effects
ggplot(all_pairs[rn %in% c('car','day:car')],
    aes(x=car_a, y=car_b)) + 
  geom_tile(
    aes(fill=-log10(p.adj))) + 
  geom_tile(
    data=all_pairs[rn %in% c('car','day:car')][p.adj < 0.05],
    color='black', fill=NA, size=1) +
  scale_fill_distiller(palette="RdPu", direction=1) +
  facet_wrap(~rn) + 
  scale_color_manual(values=c('white','black')) + 
  theme_minimal() + 
  plot_theme + 
  theme(legend.position='right')

# plot to put in the manuscript - only car effect, with significance *s

plots$exh_stats_all_pairs_plot <- ggplot(all_pairs[rn == 'car'],
    aes(x=car_a, y=car_b, 
        fill=-log10(p.adj),
      label=p.adj.signif)) + 
  geom_tile(color='white') +
  scale_fill_gradientn(colors=brewer.pal(9, 'RdPu')[1:7], 
    guide=guide_colorbar(
      barheight=0.7,
      barwidth=4,
      direction = "horizontal",
      title.position = "top")) +
  geom_text() + 
  labs(x='', y='Overall Exhaustion Marker Rank', fill='-log10(p),\nRM ANOVA') +
  theme_minimal() + 
  theme(panel.grid=element_blank(),
    legend.position=c(1,0.05),
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
    legend.justification=c(1,0))

```

### Exhaustion Summary (supp)

```{r}

get_marker_counts <- function(exh_dt, exh_vars=c('tim3_t','lag3_t', 'pd1_t','cd39_t')) {
  marker_ct <- exh_dt[!outlier_well & variable %in% exh_vars,
    list(n_pos_marker= sum(gt_thresh)),
    by=c('well','plate','day','Time','car','donor','k562','t_type')]
  
  marker_ct <- marker_ct[, N := .N, by=c('well','plate','day','car','k562','t_type')][N > 1]
  
  marker_ct <- map_day_0(marker_ct)
  
  marker_freq <- marker_ct[, data.frame(table(factor(n_pos_marker, levels= 0:length(exh_vars)))), 
    by=c('well','plate','day','car','donor','k562','t_type')]
  names(marker_freq)[names(marker_freq) == 'Var1'] <- 'n_pos_marker'
  
  marker_freq[ n_pos_marker != 7, pct := Freq/sum(Freq), 
    by=c('well','plate','day','car','donor','k562','t_type')]
  
  return(marker_freq)
}

if (!exists('supp_day_dt'))
  supp_day_dt <- get_marker_counts(
    exh_dt,
    exh_vars=c('tim3_t','lag3_t', 'pd1_t'))[
      day %in% c(0,6,15,24,33) &
      k562 == 'cd19+']

stacked_exh_plot <- function(day_dt_subset, horiz=F) {
  
  day_dt_subset <- day_dt_subset[, 
      c('mean_pct','sd_pct') := list(mean(pct), sd(pct)), 
      by=c('n_pos_marker','t_type','donor','day','k562','car')][,
        t_type := toupper(t_type)]
  
  facet_formula <- if(horiz)
    formula('donor ~ car') else formula('car ~ donor')
  
  day_dt_subset[, car := factor(car)]
  day_dt_subset[, pct := as.numeric(pct)]
  
  ggplot(unique(day_dt_subset[, list(car, mean_pct, n_pos_marker, day, t_type, donor)])) +
    geom_bar(aes(x=factor(day, levels=rev(levels(factor(day)))), y=mean_pct, fill=n_pos_marker),
      stat='identity', width=1, color='black', size=0.2) +
    facet_grid(facet_formula) +
    scale_y_continuous(expand=c(0,0), labels=label_percent()) +
    scale_x_discrete(expand=c(0,0), limits=rev) +
    scale_fill_manual(
      'Exh. Markers per cell', values=brewer.pal(9,'RdPu')[c(1,2,5,7,9)]) +
    labs(x="Days in Culture", y='Fraction of Cells') +
    theme_minimal() +
    theme(
      panel.grid=element_blank(),
      panel.border=element_rect(color='black', size=0.2, fill=NA))

}

plots$supp_exh_stacked_bars <- ((
  stacked_exh_plot(supp_day_dt[t_type == 'cd4' & day %in% c(0,6,15,24,33)][,
      donor := factor(paste0('Donor ',donor))]) +
    labs(subtitle='CD4', tag='B') +
    theme(
      panel.background = element_rect(fill='grey70'),
      legend.position='bottom',
      axis.text.y=element_blank(),
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title=element_blank())
  ) / (
  stacked_exh_plot(supp_day_dt[t_type == 'cd8' & day %in% c(0,6,15,24,33)][,
      donor := factor(paste0('Donor ',donor))]) +
    labs(subtitle='CD8', x='Day') +
    theme(
      panel.background = element_rect(fill='grey70'),
      legend.position='bottom',
      axis.text.y=element_blank(),
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title.y=element_blank())
  ) & theme(legend.position='bottom')) + 
  plot_layout(guides='collect')

plots$supp_exh_stacked_bars_horiz <- ((
  stacked_exh_plot(supp_day_dt[t_type == 'cd4' & day %in% c(0,6,15,24,33)][,
      donor := factor(paste0('Donor ',donor))],
    horiz=T) +
    labs(subtitle='CD4', tag='B') +
    theme(
      panel.background = element_rect(fill='grey70'),
      legend.position='bottom',
      axis.text.y=element_blank(),
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title=element_blank())
  ) | (
  stacked_exh_plot(supp_day_dt[t_type == 'cd8' & day %in% c(0,6,15,24,33)][,
      donor := factor(paste0('Donor ',donor))],
    horiz=T) +
    labs(subtitle='CD8', x='Day') +
    theme(
      panel.background = element_rect(fill='grey70'),
      legend.position='bottom',
      axis.text.y=element_blank(),
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title.y=element_blank())
  ) & theme(legend.position='bottom')) + 
  plot_layout(guides='collect')

indiv_marker_means_supp <- map_day_0(exh_dt)[(
    variable %in% c('tim3_t','lag3_t', 'pd1_t') &
    outlier_well==F &
    k562 == 'cd19+'
  ),
  list(
    mean_val=mean(value),
    sem_val=sqrt(var(value)/.N)),
  by=.(donor, k562, day, t_type, car, variable)]

indiv_marker_means_supp[, variable := factor(variable)]
indiv_marker_means_supp[, variable := factor(variable,
  labels=toupper(gsub('_t','',levels(variable))))]

plot_indiv_marker_t_type <- function(indiv_marker_mean_subset, horiz=F) {
  
  facet_formula <- if(horiz)
    formula('donor ~ variable') else formula('variable ~ donor')
  
  ggplot(indiv_marker_mean_subset, 
       aes(x=day, color=car, y=mean_val)) + 
  geom_line() +
  geom_linerange(
    aes(
      ymin=mean_val-sem_val/2,
      ymax=mean_val+sem_val/2,
      group=interaction(car, day, variable, donor))) +
  geom_point() +
  scale_color_manual(values=c(car_colors, untrans='grey50')) +
  facet_grid(facet_formula, scale='free_y') +
  theme_minimal() +
  theme(
    panel.border = element_rect(fill=NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position='bottom',
    strip.background = element_blank())
}

plots$supp_marker_means <- ((
  plot_indiv_marker_t_type(indiv_marker_means_supp[t_type == 'cd4'][, 
      donor := factor(paste0('Donor ',donor))][,
      variable := factor(variable, labels=levels(variable))]) +
    labs(subtitle='CD4', tag='A') +
    theme(
      legend.position='none',
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title=element_blank())
  ) / (
  plot_indiv_marker_t_type(indiv_marker_means_supp[t_type == 'cd8' & !is.na(donor)][, 
      donor := factor(paste0('Donor ',donor))]) +
    labs(subtitle='CD8', x='Day') +
    theme(
      legend.position='bottom',
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title.y=element_blank())
  ) & theme(legend.position='bottom') & guides(color=guide_legend(title='', nrow=2))) + 
  plot_layout(guides='collect')

supp_marker_means_horiz <- ((
  plot_indiv_marker_t_type(indiv_marker_means_supp[t_type == 'cd4'][, 
      donor := factor(paste0('Donor ',donor))][,
      variable := factor(variable, labels=levels(variable))],
    horiz=T) +
    labs(subtitle='CD4', tag='A') +
    theme(
      legend.position='none',
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title=element_blank())
  ) | (
  plot_indiv_marker_t_type(indiv_marker_means_supp[t_type == 'cd8' & !is.na(donor)][, 
      donor := factor(paste0('Donor ',donor))],
      horiz=T) +
    labs(subtitle='CD8', x='Day') +
    theme(
      legend.position='bottom',
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      axis.title.y=element_blank())
  ) + theme(legend.position='bottom') & guides(color=guide_legend(title='', nrow=2))) + 
  plot_layout(guides='collect')

supp_S2_2 <- (
  plots$supp_marker_means &
    theme(legend.position = 'bottom')) | 
  (plots$supp_exh_stacked_bars &
    guides(fill=guide_legend(name='CAR',
      direction = "horizontal",
      title.position = "top",
      label.position = "bottom",
      keywidth=unit(1, 'lines'),
      keyheight=unit(1, 'lines'))) &
    theme(legend.position = 'bottom'))

supp_S3_AB <- (
  supp_marker_means_horiz & theme(legend.position = 'bottom')
  ) / (
  plots$supp_exh_stacked_bars_horiz & theme(legend.position = 'bottom'))


```
## Diff Plots

### Load Differentiation Data 

```{r}

if (reload_data | !exists('diff_dt')) {
  load(file.path(local.data.dir, 'diff.sampled.Rdata'))
  #load(file.path(data_dir, 'diff.sampled.Rdata'))
  diff_dt <- fread(file.path(local.data.dir, 'diff.sampled.csv.gz'))
}

# some replicates appear to be incorrect - possibly due to evaporation or error in measurement.
# we will identify which wells are way off of the median value for the set of 3 replicates:
diff_means <- diff_dt[grep('_t',variable) & !is.na(donor), list(
  mean_val=mean(value, na.rm=T)),
  by=c('well','plate','day','variable','donor','row','col','k562','car','t_type')]

diff_means[, c('med_val','med_diff') := list(median(mean_val), (mean_val-median(mean_val))/median(mean_val)),
  by=c('day','car','k562','variable','donor','t_type')]

replicate_issue_plot <- ggplot(map_day_0(diff_means)) + geom_histogram(aes(x=abs(med_diff), fill=factor(col %% 3), y=..density..)) + facet_grid(donor + day ~ variable + t_type + k562) + labs(x='% Difference of each replicate from median', y='Measurements') + scale_fill_discrete('replicate #') + scale_x_continuous(labels=label_percent(), oob=scales::oob_squish, limits=c(0,0.33), breaks=c(0,0.30)) + theme_minimal() + theme(panel.grid=element_blank(), panel.border = element_rect(fill=NA, color='grey50')) + geom_vline(xintercept=0.25, linetype=2, color='grey50')

diff_means[, oob := abs(med_diff) >= 0.15]
diff_means[, n_oob := sum(oob), list(donor,k562,day,t_type,car,well,plate,variable)]

outlier_wells <- unique(diff_means[n_oob == 1, list(donor,k562,day,t_type,car,well,plate)])

diff_dt <- outlier_wells[, outlier_well := T][diff_dt, on=.(donor,k562,day,t_type,car,well,plate)]
diff_dt[is.na(outlier_well), outlier_well := F]

diff_dt <- diff_dt[outlier_well == F]

```

### CD27 Expression - Lines

```{r}
plots$cd27_lines <- ggplot(
    map_day_0(diff_dt)[variable=='cd27_t' & k562 == 'cd19+' &
        value > censor_negative_min & t_type == 'cd8'][,
            list(val_sd= sd(value), val_mean= mean(value)),
        by=.(car, day, donor, variable, t_type)][
            car %in% c('BAFF-R','41BB','CD28','TACI','untrans') & 
                (donor == 2 | (donor == 1 & day < 33))][, donor := paste('Donor',donor)], 
    aes(x=day, y=val_mean/1000, 
        ymin=(val_mean-val_sd)/1000, 
        ymax=(val_mean+val_sd)/1000, color=car, group=car, linetype=car)) + 
    geom_point() + 
    geom_line() + 
    facet_grid(~ donor, scale='free_x') + 
    scale_x_continuous(breaks=c(0,6,15,24,33)) +
    scale_y_continuous(limits=c(1.25,2.4)) +
    scale_color_manual(
        values=c(car_colors,'untrans'='grey30')) +
    scale_linetype_manual(
      values=c(setNames(rep(1, length(car_colors)),names(car_colors)), 'untrans'=3)) +
    theme_minimal(base_size=9) + 
    geom_vline(xintercept=-Inf) + 
    geom_hline(yintercept=-Inf) +
    labs(y='CD27 log MFI (AU)', x='Days in culture')

plots$cd27_lines_expanded <- ggplot(
    map_day_0(diff_dt)[variable=='cd27_t' & k562 == 'cd19+' &
        value > censor_negative_min][,
            list(val_sd= sd(value)/sqrt(.N), val_mean= mean(value)),
        by=.(car, day, donor, variable, t_type, k562)][
                (donor == 2 | (donor == 1 & day < 33))][, donor := paste('Donor',donor)], 
    aes(x=day, y=val_mean/1000, 
        ymin=(val_mean-val_sd)/1000, 
        ymax=(val_mean+val_sd)/1000, color=car, group=car)) + 
    geom_point() + 
    geom_line() + 
    geom_linerange() +
    facet_grid(t_type ~ donor, scale='free') + 
    scale_color_manual(
        values=c(car_colors,'grey50')) +
    scale_linetype_manual(
        values=c(1,1,1,1,1,1,1,3,1)) +
    theme_minimal() +
    theme(panel.border=element_rect(fill=NA), panel.grid=element_blank()) +
    labs(y='CD27 log MFI (AU)', x='Days in culture')

cd27_lines_expanded_vert_func <- function(this_t_type) ggplot(
    map_day_0(diff_dt)[variable=='cd27_t' & k562 == 'cd19+' & t_type == this_t_type & 
        value > censor_negative_min][,
            list(val_sd= sd(value)/sqrt(.N), val_mean= mean(value)),
        by=.(car, day, donor, variable, k562)][
                (donor == 2 | (donor == 1 & day < 33))][, donor := paste('Donor',donor)], 
    aes(x=day, y=val_mean, 
        ymin=(val_mean-val_sd), 
        ymax=(val_mean+val_sd), color=car, group=car)) + 
    geom_point() + 
    geom_line() + 
    geom_linerange() +
    facet_wrap(donor ~ ., scale='free', ncol=1) + 
    scale_color_manual(
        values=c(car_colors,'grey50')) +
    scale_linetype_manual(
        values=c(1,1,1,1,1,1,1,3,1)) +
    theme_minimal() +
    theme(panel.border=element_rect(fill=NA), panel.grid=element_blank()) +
    labs(y='CD27 MFI (AU)', x='Days in culture')

plots$cd27_lines_combined <- (
  (cd27_lines_expanded_vert_func('cd4') + theme(
    legend.position='none', axis.title.x=element_blank()))) /
  (cd27_lines_expanded_vert_func('cd8') + theme(
    legend.position='none')
)
```

### CD27 Expression - Ridges

```{r}

make_ridge_plot_panel <- function(df, var, show_line=F) {
  
  df[, car := factor(car, levels=car_order)]
  
  df_ct <- df[, .N, by=c(c('day','car','donor','k562'))]
  
  var_disp = toupper(gsub('(.*)_t','\\1',var))
  
  p <- ggplot(df[variable == var & value < 3200]) + 
  geom_density_ridges(
    aes(y=factor(car, levels=rev(car_order)), x=value, color=car, fill=car, height=..ndensity..), 
    alpha=0.7, scale=1) +
  facet_grid( ~ t_type + day, switch="both") +
  xlim(c(600, NA)) +
  theme_minimal() +
  scale_fill_manual(values=rev(car_colors)) +
  scale_y_discrete(expand=c(0.05,0.01)) +
  scale_color_manual(values=rev(car_colors))

  
  if (show_line) {
    p <- p + geom_vline(xintercept=df[[var]])
  }
       
  return(p)
}

#colors 
grey_shades <- c(
  "#ECECEC",
  "#B7B7B7",
  "#828282",
  "#4D4D4D")
darkblue_shades <- c(
  "#E9F0F6",
  "#ACC5DE",
  "#719AC7",
  "#3A6FB0")
lightblue_shades <- c(
  "#F0F6FA",
  "#C8DDEC",
  "#A1C4DF",
  "#7BACD2")
lightgreen_shades <- c(
  "#F2F9F2",
  "#CDE6CA",
  "#AAD5A4",
  "#87C27E")
darkgreen_shades <- c(
  "#EAF2EC",
  "#AFCEB6",
  "#76AD81",
  "#45894C")

cd27_car_name_set <- paste(rep(c('untrans','CD28','41BB','BAFF-R','TACI'), each = 4), c(0,6,15,24), sep = ".")
cd27_car_colors <- c(grey_shades, darkblue_shades, lightblue_shades, lightgreen_shades, darkgreen_shades) 

cd27_car_colors <- setNames(cd27_car_colors, cd27_car_name_set)

diff_display_dt <- map_day_0(diff_dt)[
  variable=='cd27_t' & k562 == 'cd19+' & value > -500 & t_type == 'cd8'][
    car %in% c('BAFF-R','41BB','CD28','TACI','untrans') & 
      (day < 33)][, donor := paste('Donor',donor)][,
        car := factor(car, levels=c('untrans',car_order))]

vline_pos <- 2000

diff_pct_dt <- diff_display_dt[, list(
  pct=sum(value > vline_pos)/.N * 100),
  by=c('donor','day','car')]


plots$cd27_ridges <- ggplot(diff_display_dt) +
    geom_density_ridges(aes(x=value, y=factor(day), fill=interaction(car,day), color=car,
      height =..ndensity..), scale=1.5) +
    geom_text(data=diff_pct_dt, aes(x=3200, y=factor(day), color=car, label=round(pct,0)), vjust=-0.5) +
    coord_cartesian(clip='off') +
    scale_alpha_discrete(guide='none') +
    scale_fill_manual(guide='none',values=cd27_car_colors) +
    scale_color_manual(guide='none',values=c(car_colors,'untrans'='grey30')) +
    facet_grid(car~donor, scales='free') +
    scale_x_continuous(limits=c(0, 3200), expand=c(0.15,10)) +
    scale_y_discrete(expand=c(0,0), limits=rev) +
    theme_minimal(base_size=9) + 
    theme(panel.border=element_rect(fill=NA), panel.grid=element_blank()) +
    labs(x='CD27 log MFI (AU)', y='Days in culture') +
    geom_vline(aes(xintercept=vline_pos), linetype=2)

plots$cd27_lines
plots$cd27_lines_expanded
plots$cd27_ridges
```

### CD27 stats

```{r}

# model is significant:
aov(formula=pct~day*car + Error(donor), data=diff_pct_dt)

#post-hoc pairwise
#BB/BAFFR significant (p=.019)
summary(aov(formula=pct~day*car + Error(donor), data=diff_pct_dt[car %in% c('41BB','BAFF-R')]))
#28/BAFFR NOT significant (p=.2)
summary(aov(formula=pct~day*car + Error(donor), data=diff_pct_dt[car %in% c('CD28','BAFF-R')]))
#BB TACI significant
summary(aov(formula=pct~day*car + Error(donor), data=diff_pct_dt[car %in% c('41BB','TACI')]))
#28 TACI significant
summary(aov(formula=pct~day*car + Error(donor), data=diff_pct_dt[car %in% c('CD28','TACI')]))
#...
# added this to illustrator plot



```

### Diff Markers Supp 

```{r}

fcs_flags <- dcast(
  diff_dt[!is.na(gt_thresh) & outlier_well==F],
  donor + k562 + day + t_type + car + well + plate + outlier_well + event_id + col + row ~ variable, 
  value.var='gt_thresh')[
    !is.na(donor) & !is.na(day)]

names(fcs_flags) <- gsub('(.*)_t','\\1',names(fcs_flags))

fcs_flags[,
  `:=`(
    cd62_cd45ro_diff= factor(
      cd45ro + 2*cd62l),
    cd62_cd45ra_diff= factor(
      cd62l + 2*cd45ra),
    cd45ra_ccr7_diff= factor(
      cd45ra + 2*ccr7),
    cd45ro_ccr7_diff= factor(
      cd45ro + 2*ccr7),
    cd45ro_cd27_diff= factor(
      cd45ro + 2*cd27),
    cd62_cd27_diff= factor(
      cd62l + 2*cd27)
  )]


levels(fcs_flags$cd62_cd45ra_diff) <- c('TEM','TCM','TEMRA','Naive')
levels(fcs_flags$cd62_cd45ro_diff) <- c('TEMRA','TEM','Naive','TCM')
levels(fcs_flags$cd45ra_ccr7_diff) <- c('TEM','TEMRA','TCM','Naive')
levels(fcs_flags$cd45ro_ccr7_diff) <- c('TEMRA','TEM','Naive','TCM')
levels(fcs_flags$cd45ro_cd27_diff) <- c(
  'CD45RO-/CD27-','CD45RO+/CD27-','CD45RO-/CD27+','CD45RO+/CD27+')
levels(fcs_flags$cd62_cd27_diff) <- c(
  'CD62L-/CD27-','CD62L+/CD27-','CD62L-/CD27+','CD62L+/CD27+')

diff_marker_dt <- melt.data.table(
    fcs_flags,
    measure.vars= c(
        'cd62_cd45ra_diff', 'cd62_cd45ro_diff', 
        'cd45ro_ccr7_diff', 'cd45ra_ccr7_diff',
        'cd45ro_cd27_diff', 'cd62_cd27_diff',
        'cd62l', 'cd27', 'ccr7', 'cd45ro', 'cd45ra', 'cd95'))

make_diff_percent_dt <- function(dt, diff_set) {
  
  subset_dt <- map_day_0(
    dcast(dt[variable == diff_set],
    ... ~ variable, value.var='value'))
  subset_dt[, c(diff_set) := factor(get(diff_set))]
  
  subset_dt <- subset_dt[, 
    reshape2::melt(table(get(diff_set))),
    by=c('car', 'donor', 'day', 'k562', 'well', 'plate', 'type')][,
      frac := value/sum(value),
      by=c('car', 'donor', 'day', 'k562', 'well', 'plate', 'type')]
  names(subset_dt) <- gsub('V1', 'value', names(subset_dt))
  names(subset_dt) <- gsub('Var1', 'diff', names(subset_dt))
  
  diff_mean_dt <- subset_dt[!is.na(donor), list(
      val_mean= mean(frac), 
      val_sd= sd(frac)), 
      by=c('car','k562','donor','day','diff','type')]

  return(diff_mean_dt)
}

cd62_cd45ra_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd62_cd45ra_diff')
cd62_cd45ro_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd62_cd45ro_diff')
cd45ra_ccr7_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd45ra_ccr7_diff')
cd45ro_ccr7_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd45ro_ccr7_diff')
cd45ro_cd27_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd45ro_cd27_diff')
cd27_dt <- make_diff_percent_dt(diff_marker_dt, 'cd27')
cd95_dt <- make_diff_percent_dt(diff_marker_dt, 'cd95')


plot_by_day <- function(diff_mean_dt, title, formula_txt='car~k562+donor+type') {
  return(
    ggplot(diff_mean_dt[, car := factor(car, levels=c(car_order, 'untrans'))][,
        donor := factor(paste0('Donor ',donor))]) + 
      geom_bar(aes(x=as.factor(day), y=val_mean, fill=diff),
        stat='identity', position='stack', width=1, color='black', size=0.2) +
      scale_fill_manual(values=hcl.colors(4,'Temps')) +
      facet_grid(as.formula(formula_txt)) + 
      scale_y_continuous(expand=c(0,0), labels=label_percent()) +
      scale_x_discrete(expand=c(0,0)) +
      theme_minimal() +
      theme(
        panel.grid=element_blank(),
        panel.border=element_rect(color='black', size=0.2, fill=NA)) +
      labs(x='Day', y='% Subset', title=title))
}

all_diff_plots <- (
  plot_by_day(
    cd62_cd45ra_diff_dt[k562=='cd19+'], 'CD62L vs CD45RA differentiation') |
  plot_by_day(
    cd62_cd45ro_diff_dt[k562=='cd19+'], 'CD62L vs CD45RO differentiation') |
  plot_by_day(
    cd45ra_ccr7_diff_dt[k562=='cd19+'], 'CD45RA vs CCR7 differentiation') |
  plot_by_day(
    cd45ro_ccr7_diff_dt[k562=='cd19+'], 'CD45RO vs CCR7 differentiation'))

plots$diff_supp <- (
  (plot_by_day(
    cd62_cd45ra_diff_dt[k562=='cd19+' & type == 'cd4' &
      !(car == 'untrans' & day == 33 & donor == 2)],
      'CD62L vs CD45RA differentiation', formula_txt='car~donor') +
    labs(subtitle='CD4') +
    theme(
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      panel.background = element_rect(fill='grey70'),
      legend.position='none',
      axis.text.x=element_blank(),
      plot.title=element_blank(),
      axis.text.y=element_blank())) /
  (plot_by_day(
    cd62_cd45ra_diff_dt[k562=='cd19+' & type == 'cd8'],
      'CD62L vs CD45RA differentiation', formula_txt='car~donor') +
    labs(subtitle='CD8') +
    guides(fill=guide_legend(title='',
      direction = "horizontal",
      title.position = "top",
      label.position = "bottom",
      keywidth=unit(1, 'lines'),
      keyheight=unit(1, 'lines')))) +
    theme(
      plot.subtitle = element_text(hjust=0.5, margin=margin(0,0,0,0,'pt')),
      panel.background = element_rect(fill='grey70'),
      plot.title=element_blank(),
      legend.position='bottom',
      axis.text.y=element_blank())
)

```

### Metab Placeholder Plot

```{r}

metab_dt <- fread(text="
  t_type,41BB,BAFF-R,CD28,TACI,zeta
  CD4,0.48398212,1.00948129,-0.365573,-0.5706298,-1.9264523
  CD8,0.37320327,0.92599065,0.06335877,-1.8369371,-0.5431782")

metab_dt <- melt(metab_dt, id.var='t_type', variable.name = 'car', value.name='zscore')

metab_dt[, car.ordered := reorder(interaction(car,t_type), -zscore)]


metab_horiz <- ggplot(metab_dt) +
  geom_bar(aes(
    x=car.ordered,
    y=zscore,
    fill=car), stat='identity') +
  facet_grid(~t_type, scales='free') +
  scale_fill_manual(values=car_colors) + 
  scale_x_discrete(labels=function (x) gsub('\\.CD\\d','',x)) +
  theme_minimal() +
  theme(
    axis.text.x=element_text(angle = 90, hjust = 1, vjust=0.5),
    panel.border=element_rect(color='black', fill=NA),
    panel.grid=element_blank(),
    legend.position='none') +
  labs(x='',y='Mitochondrial Metabolic Dependence (Z-score)')

metab_vert <- ggplot(metab_dt) +
  geom_bar(aes(
    x=factor(car, levels=c('BAFF-R','41BB','CD28','TACI','zeta')),
    y=zscore, fill=car, color=car), stat='identity', alpha=0.8) +
  facet_grid(t_type~., scales='free') +
  scale_fill_manual(values=car_colors) +
  scale_color_manual(values=car_colors) + 
  scale_x_discrete(labels=function (x) gsub('\\.CD\\d','',x)) +
  theme_minimal() +
  geom_hline(yintercept=0, linetype=2) +
  theme(
    axis.text.x=element_text(angle = 90, hjust = 1, vjust=0.5),
    panel.border=element_rect(color='black', fill=NA),
    panel.grid=element_blank(),
    legend.position='none') +
  labs(x='',y='Mitochondrial Metabolic\nDependence(Z-score)')

metab_vert
```

## Compile Fig 4

```{r}

fig4_compiled <- # C, D, E
  ((
    plot_spacer() /
    traces_horiz
  ) + plot_layout(heights=c(0.1,0.8)) |
  # F and G
  (
    (
      #D
      (cd4_expansion_plot + 
         guides(color='none', shape='legend') +
         theme(
          legend.position='bottom',
          plot.title = element_blank(),
          panel.grid=element_blank())) / 
      #E
      plot_spacer() / 
      #F
      (
        plots$exh_stacked_bars & theme(
          legend.position='top')
      ) + 
      plot_layout(heights=c(1,0.75,2)) + 
      plot_annotation(tag_levels=list(c('F','G')))
    ) |
    # H
    (
      plots$cd27_ridges + 
        theme(axis.ticks.x=element_line()) + 
        plot_annotation(tag_levels=list(c('H')))
    )
  )) + plot_layout(widths=c(0.4,0.6))

# remove grids,
# top right square
# % PD1 positive
# donor legend for CD40
# remove ticks for A
# enclose B in box

ggsave(here::here('..','figs','compiled','fig4.newdraft.pdf'), fig4_compiled, height=8, width=10, useDingbats=FALSE)
```

## Compile S4

```{r}
figS4_compiled <- (
  (plots$ctv_supp | metab_vert) /
  ((supp_S2_2 |
    (
      (plots$exh_stats_all_pairs_plot / plots$cd27_lines_combined) + 
       plot_layout(heights=c(1,3))) |
    plots$diff_supp) + 
    plot_layout(widths=c(1,1,1,1.1))) +
     plot_layout(heights=c(1,5)))

fig_scaling <- 1.7
ggsave(here::here('..','figs','compiled','figS4.newdraft.pdf'), figS4_compiled,
       height=8.5*fig_scaling, width=7*fig_scaling, useDingbats=FALSE)
```
