---
title: "Differentiation Plots for Arrayed Screens"
output:
  html_document:
    df_print: paged
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here('..','html'))})
---

## Load packages and umap functions 
```{r setup}
library(ggplot2)
library(data.table)
library(scales)
library(RColorBrewer)
library(reticulate)
library(uwot)
library(gridExtra)
library(spatstat)
library(ggdendro)
library(cowplot)
library(tidyverse)
library(grid)
library(gridExtra) # add to AWS
library(cowplot) # add to AWS
library(slingshot) # add to AWS
library(viridis) # add to AWS
library(reshape2)
library(RColorBrewer)
library(ggrepel)

source('umap.R')

use_condaenv(condaenv = 'r-reticulate', required = TRUE)
```

## Load data
```{r}
data_dir <- here::here('..','data')
fig_dir <- here::here('..','figs','umap')
load(file.path(data_dir, 'exh.sampled.Rdata'))
exh_dt <- fread(file.path(data_dir, 'exh.sampled.csv.gz'))

censor_negative_min = -1500
redo_umap_clustering = F
redo_umap_param_search = F

#only redo param search if doing clustering also:
redo_umap_param_search = redo_umap_param_search && redo_umap_clustering

# map day 0 to both plus and minus
map_day_0 <- function(df) {
  return(rbind(
    df[k562!='none'],
    df[k562=='none'][, k562 := 'cd19+'],
    df[k562=='none'][, k562 := 'cd19-']
  ))
}

censor_negative_min = -1500
redo_umap_clustering = F
redo_umap_param_search = F

```

## UMAP Plot Functions

```{r, fig.width=20, fig.height=12}
save_plots <- function(subset_dt, cell_type, prefix, plot_width=20, plot_height=12) {
  
  #grab channel map from cd4 data (cd4/8 are the same)
  channel_map <- exh_opt_cd4$channel_map
  
  # for now use all variables in the channel map except cd4/8
  umap_vars <- c(paste0(names(channel_map),'_t'))
  
  # removing zombie, cd_t, myc_t, gfp_t
  umap_vars <- umap_vars[!umap_vars %in% c('cd_t', 'zombie_t', 'myc_t', 'gfp_t')]
  umap_fcs_dt <- run_umap(subset_dt, 0.005, 15, 1000, umap_vars)
  
  file_prefix <- paste0(fig_dir,'/', prefix)
  
  ggsave(paste0(file_prefix, '.umap_overview.pdf'), ggumap(umap_fcs_dt), width=plot_width, height=plot_height)
  ggsave(paste0(file_prefix, '.umap_per_day_car.pdf'), color_plots(umap_fcs_dt), width=plot_width, height=plot_height)
  ggsave(paste0(file_prefix, '.umap_density.pdf'), umap_contour_plots(umap_fcs_dt), width=plot_width, height=plot_height)
  ggsave(paste0(file_prefix, '.umap_components.pdf'), all_plots(umap_fcs_dt, cell_type), width=plot_width, height=plot_height)
}
```

## Censor data if not in both donors, for joint plots
```{r}

#cd4, cd19+, donor 
exh_dt_cd4 <- exh_dt %>% map_day_0() %>% filter(t_type == 'cd4', k562=='cd19+')

#cd8, cd19+, donor
exh_dt_cd8 <- exh_dt %>% map_day_0() %>% filter(t_type == 'cd8', k562=='cd19+')

## Remove car/day combinations that aren't in both donors, by t_type
cd4_matches <- plyr::match_df(exh_dt %>% map_day_0 %>% filter(t_type == 'cd4', donor == 2, k562=='cd19+') %>% 
  filter(!is.na(event_id)) %>% distinct(car, day), diff_dt %>% map_day_0 %>% 
  filter(t_type == 'cd4', donor == 1, k562=='cd19+') %>% 
  filter(!is.na(event_id)) %>% distinct(car, day)) %>% 
  arrange(day) #43 matches

cd8_matches <- plyr::match_df(exh_dt %>% map_day_0 %>% 
  filter(t_type == 'cd8', donor == 2, k562=='cd19+') %>% 
  filter(!is.na(event_id)) %>% distinct(car, day), diff_dt %>% map_day_0 %>% 
  filter(t_type == 'cd8', donor == 1, k562=='cd19+') %>% 
  filter(!is.na(event_id)) %>%distinct(car, day)) %>% 
  arrange(day) #40 matches

#filter exh_dt by matched combinations
exh_dt_cd4_comb <- plyr::match_df(exh_dt_cd4, cd4_matches)
exh_dt_cd8_comb <- plyr::match_df(exh_dt_cd8, cd8_matches)
```

## Save Plots
```
save_plots(
  subset_dt = exh_dt_cd8_comb,
  cell_type = 'CD8 Combined',
  prefix = 'CD8.comb',
  plot_height = 12,
  plot_width = 20
)

save_plots(
  subset_dt = exh_dt_cd4_comb,
  cell_type = 'CD4 Combined ',
  prefix = 'CD4.comb',
  plot_height = 12,
  plot_width = 20
)


save_plots(
  subset_dt = map_day_0(exh_dt)[t_type == 'cd8' & k562 == 'cd19+' & donor == 1],
  cell_type = 'CD8 Donor 1',
  prefix = 'CD8.d1',
  plot_height = 12,
  plot_width = 20
)

save_plots(
  subset_dt = map_day_0(exh_dt)[t_type == 'cd8' & k562 == 'cd19+' & donor == 1],
  cell_type = 'CD8 Donor 1',
  prefix = 'CD8.d1',
  plot_height = 12,
  plot_width = 20
)

save_plots(
  subset_dt = map_day_0(exh_dt)[t_type == 'cd8' & k562 == 'cd19+' & donor == 2],
  cell_type = 'CD8 Donor 2',
  prefix = 'CD8.d2',
  plot_height = 12,
  plot_width = 20
)

save_plots(
  subset_dt = map_day_0(exh_dt)[t_type == 'cd4' & k562 == 'cd19+' & donor == 1],
  cell_type = 'CD4 Donor 1',
  prefix = 'CD4.d1',
  plot_height = 12,
  plot_width = 20
)

save_plots(
  subset_dt = map_day_0(exh_dt)[t_type == 'cd4' & k562 == 'cd19+' & donor == 2],
  cell_type = 'CD4 Donor 2',
  prefix = 'CD4.d2',
  plot_height = 12,
  plot_width = 20
)


```

