---
title: "Differentiation"
output:
  html_document:
    df_print: paged
---

```{r}
require(data.table)
require(ggplot2)
require(scales)
require(here)
require(flowCore)
require(flowWorkspace)
require(ggcyto)
require(RColorBrewer)

parent_folder = here::here('..')
```

## Myc to GFP

```{r, fig.width=18, fig.height=7}

map_day_0_diff <- function(df) {
  return(rbind(
    df[k562!='none'],
    df[k562=='none'],
    df[k562=='none' & day == 0][, k562 := 'cd19+'],
    df[k562=='none' & day == 0][, k562 := 'cd19-']
  ))
}

diff_cast_dt <- dcast(diff_dt[!is.na(value)],
  t_type + donor + k562 + day + car + well + plate + event_id + col + row ~ variable,
  value.var='value')

mfi_myc_summ <- melt(diff_cast_dt[!is.na(car) & car != 'untrans', list(
  myc_to_gfp=mean(myc_t/gfp_t),
  gfp=mean(gfp_t),
  myc=mean(myc_t)),
  by=c('car','donor','day','k562','t_type')], id.vars=c('car','donor','day','k562','t_type'))[,
    value_norm := value/mean(value), by=c('variable')]

myc_average_exp <- map_day_0_diff(mfi_myc_summ)[,
  list(car, value_norm_day= value/mean(value)), 
  by=c('variable','day','donor','k562','t_type')][,
    list(car, value_avg= value_norm_day/mean(value_norm_day)),
  by=c('variable','k562','t_type')][,
    car := factor(car, levels=car_order)][variable == 'myc']


ggplot(myc_average_exp[,
    k562 := factor(k562, levels=levels(factor(k562)), labels=c('CD19+ K562s','CD19- K562s','No K562s'))
    ],
    aes(
      x=car, fill=car, y=value_avg, color=car, group=(interaction(car,k562)))) + 
  geom_boxplot(alpha=0.5) +
  scale_y_continuous(label=label_percent(accuracy=1)) +
  scale_color_manual('', values=car_colors) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  scale_fill_manual('', values=car_colors) +
  facet_grid( ~  k562, scale='free') +
      theme_minimal() +
geom_vline(xintercept=-Inf) + 
geom_hline(yintercept=-Inf)  +
theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank()) +
  labs(y='Rel. change from mean',
       x='CAR', title='CAR expression differences') +
  geom_hline(yintercept=1, linetype=3, color='grey50')

```

## Gating Strategies

```{r fig.width=18, fig.height=7}

## First, set the cutoffs for each channel

# choose thresholds visually (plotted below)
marker_pos_threshold <- list(
  cd62l=flowJoTrans(inverse=T)(1800),
  cd27=flowJoTrans(inverse=T)(1800),
  ccr7=flowJoTrans(inverse=T)(1050),
  cd45ro=flowJoTrans(inverse=T)(1100),
  cd45ra=flowJoTrans(inverse=T)(1100),
  cd95=flowJoTrans(inverse=T)(2100))

marker_thresh_dt <- data.table(
  variable= paste0(names(marker_pos_threshold),'_t'),
  threshold= flowJoTrans()(unlist(marker_pos_threshold)))

# assess marker thresholds
ggplot(diff_dt[
    variable %in% paste0(names(channel_map),'_t')]) + 
  geom_density(aes(x=value, color=factor(day), linetype=k562)) + 
  scale_x_continuous(limits=c(-1000,5000)) +
  facet_grid(k562+donor+t_type~variable, scale='free') + 
  scale_color_manual(values=brewer.pal(7, "YlGnBu")[3:7]) +
  geom_vline(data=marker_thresh_dt, aes(xintercept=threshold))
```

## Examine pairs of markers
```{r, fig.width=18, fig.height=7}

fcs_melt_sample_dt <- diff_dt

# this function assigned 'none' k562 group to baseline day 0
map_day_0 <- function(df) {
  return(rbind(
    df[k562!='none'],
    df[k562=='none'][, k562 := 'cd19+'],
    df[k562=='none'][, k562 := 'cd19-']
  ))
}

cast_vars <- function(df, cast_vars) {
  return(
    dcast(map_day_0(df[variable %in% cast_vars]), 
      well + plate + day + car + k562 + donor + event_id ~ variable,
      value.var='value'))
}

plot_2d_density_vars <- function(df, x_var, y_var) {

  cast_dt <- data.table(cast_vars(df, cast_vars=c(x_var, y_var)))
  
  x_threshold <- marker_thresh_dt[variable==x_var, threshold]
  y_threshold <- marker_thresh_dt[variable==y_var, threshold]
  
  thresh_dt <- cast_dt[, melt(table(
    x_thresh= (get(x_var) > x_threshold),
    y_thresh= (get(y_var) > y_threshold))),
    by=c('k562','car')]
  
  thresh_dt[, frac := value/sum(value), by=c('k562','car')]
  
  quadrant_labels <- data.table(
    x=c(Inf,Inf,-Inf,-Inf),
    y=c(Inf,-Inf,Inf,-Inf),
    x_thresh=c(T, T, F, F),
    y_thresh=c(T, F, T, F),
    hjust=c(1,1,0,0),
    vjust=c(1,0,1,0)
  )
  
  thresh_dt <- thresh_dt[quadrant_labels, on=c('x_thresh','y_thresh')]
  thresh_dt[, pct := percent(round(frac,2))]
  
  plot <- ggplot(cast_dt) + 
    geom_density2d(aes(y=get(y_var), x=get(x_var)), n=200) + 
    facet_grid(k562~car) + 
    scale_x_continuous(limits=c(-1000,4000)) + 
    scale_y_continuous(limits=c(-1000,4000)) + 
    geom_vline(xintercept=x_threshold) + 
    geom_hline(yintercept=y_threshold) +
    geom_text(data=thresh_dt, aes(x=x, y=y, label=pct, hjust=hjust, vjust=vjust))
  
  return(plot)
}

plot_2d_density_vars_split_donor <- function(df, x_var, y_var, tile=F) {

  cast_dt <- data.table(cast_vars(df, cast_vars=c(x_var, y_var)))
  
  x_threshold <- marker_thresh_dt[variable==x_var, threshold]
  y_threshold <- marker_thresh_dt[variable==y_var, threshold]
  
  thresh_dt <- cast_dt[, melt(table(
    x_thresh= (get(x_var) > x_threshold),
    y_thresh= (get(y_var) > y_threshold))),
    by=c('k562','car','donor')]
  
  thresh_dt[, frac := value/sum(value), by=c('k562','car','donor')]
  thresh_dt[, pct := percent(frac,accuracy=1)]

  quadrant_labels <- data.table(
    x=c(Inf,Inf,-Inf,-Inf),
    y=c(Inf,-Inf,Inf,-Inf),
    x_thresh=c(T, T, F, F),
    y_thresh=c(T, F, T, F),
    hjust=c(1,1,0,0),
    vjust=c(1,0,1,0)
  )
  
  thresh_dt <- thresh_dt[quadrant_labels, on=c('x_thresh','y_thresh')]
  
  if (tile) {
  
    tile_plot <- ggplot(thresh_dt, aes(y=y_thresh, x=x_thresh)) + 
      geom_tile(aes(fill=frac)) + 
      facet_grid(k562+donor~car) + 
      scale_fill_distiller(palette='Greens', direction=1) + 
      geom_text(aes(label=pct), size=3) +
      scale_x_discrete(x_var, labels=c('-','+')) +
      scale_y_discrete(y_var, labels=c('-','+')) +
      theme_minimal()
    
    return(tile_plot)
  } else {
    plot <- ggplot(cast_dt) + 
      geom_density2d(aes(y=get(y_var), x=get(x_var)), n=200) + 
      facet_grid(k562+donor~car) + 
      scale_x_continuous(x_var, limits=c(-1000,4000)) + 
      scale_y_continuous(y_var, limits=c(-1000,4000)) + 
      geom_vline(xintercept=x_threshold) + 
      geom_hline(yintercept=y_threshold) +
      geom_text(data=thresh_dt, aes(x=x, y=y, label=pct, hjust=hjust, vjust=vjust))
    
    return(plot)
  }
}


plot_2d_density_vars(fcs_melt_sample_dt[day==6], y_var='ccr7_t', x_var='cd45ro_t') +
  labs(x='CD45RO', y='CCR7',title='Day 6 CCR7 vs CD45RO Diff')

plot_2d_density_vars(fcs_melt_sample_dt[day==33], y_var='ccr7_t', x_var='cd45ra_t') +
  labs(x='CD45RA', y='CCR7',title='Day 33 CCR7 vs CD45RA Diff')

plot_2d_density_vars(fcs_melt_sample_dt[day==6], y_var='cd45ra_t', x_var='cd62l_t') +
  labs(y='CD45RA', x='CD62L',title='Day 6 CD45RA vs CD62L Diff')

plot_2d_density_vars(fcs_melt_sample_dt[day==6], y_var='cd45ra_t', x_var='cd45ro_t') +
  labs(y='CD45RA', x='CD45RO',title='Day 6 CD45RO vs CD45RA')

plot_2d_density_vars(fcs_melt_sample_dt[day==33], x_var='cd45ro_t', y_var='cd27_t') +
  labs(x='CD45RO', y='CD27',title='Day 33 CD45RO vs CD27 Diff')


fcs_flags <- fcs_dt[,
  list( 
    car, donor, day, k562, Time, well, plate, event_id,
    cd62l= cd62l > marker_pos_threshold$cd62l,
    cd27= cd27 > marker_pos_threshold$cd27,
    ccr7= ccr7 > marker_pos_threshold$ccr7,
    cd45ro= cd45ro > marker_pos_threshold$cd45ro,
    cd45ra= cd45ra > marker_pos_threshold$cd45ra,
    cd95= cd95 > marker_pos_threshold$cd95)]

fcs_flags[,
  `:=`(
    cd62_cd45ra_diff= factor(
      cd62l + 2*cd45ra),
    cd45ra_ccr7_diff= factor(
      cd45ra + 2*ccr7),
    cd45ro_ccr7_diff= factor(
      cd45ro + 2*ccr7),
    cd45ro_cd27_diff= factor(
      cd45ro + 2*cd27),
    cd62_cd27_diff= factor(
      cd62l + 2*cd27)
    )]


levels(fcs_flags$cd62_cd45ra_diff) <- c('TEM','TCM','TEMRA','Naive')
levels(fcs_flags$cd45ra_ccr7_diff) <- c('TEM','TEMRA','TCM','Naive')
levels(fcs_flags$cd45ro_ccr7_diff) <- c('TEMRA','TEM','Naive','TCM')
levels(fcs_flags$cd45ro_cd27_diff) <- c(
  'CD45RO-/CD27-','CD45RO+/CD27-','CD45RO-/CD27+','CD45RO+/CD27+')
levels(fcs_flags$cd62_cd27_diff) <- c(
  'CD62L-/CD27-','CD62L+/CD27-','CD62L-/CD27+','CD62L+/CD27+')

diff_marker_dt <- melt.data.table(
    fcs_flags,
    measure.vars= c(
        'cd62_cd45ra_diff', 'cd45ro_ccr7_diff', 'cd45ra_ccr7_diff',
        'cd45ro_cd27_diff', 'cd62_cd27_diff',
        'cd62l', 'cd27', 'ccr7', 'cd45ro', 'cd45ra', 'cd95'))

tile_set <- function(df, exh_x, exh_y, days=c(0,6,15,24,33)) {
  plot_grid(
    plot_grid(plotlist=lapply(days, function(day_i) 
      plot_2d_density_vars_split_donor(
        df[t_type == 'cd4' & day==day_i], 
        y_var=exh_x, x_var=exh_y, tile=F) + 
        ggtitle(paste('CD4 Day', day_i))), ncol=1),
    plot_grid(plotlist=lapply(days, function(day_i) 
      plot_2d_density_vars_split_donor(
        df[t_type == 'cd8' & day==day_i], 
        y_var=exh_x, x_var=exh_y, tile=F) + 
        ggtitle(paste('CD8 Day', day_i))), ncol=1)
  )
}


# plot_grid(plot_grid(plotlist=lapply(c(0,6,15), function(day_i) plot_2d_density_vars_split_donor(diff_mdz_dt[k562 == 'cd19-' & t_type == 'cd4' & day==day_i & car %in% c('41BB','BAFF-R','CD28')], y_var='ccr7_t', x_var='cd62l_t', tile=F) + ggtitle(paste('CD4 Day', day_i))), ncol=1),plot_grid(plotlist=lapply(c(0,6,15), function(day_i) plot_2d_density_vars_split_donor(diff_mdz_dt[k562 == 'cd19-' & t_type == 'cd8' & day==day_i & car %in% c('41BB','BAFF-R','CD28')], y_var='ccr7_t', x_var='cd62l_t', tile=F) + ggtitle(paste('CD8 Day', day_i))), ncol=1))

```

### Diff Plot Functions

```{r, fig.width=18, fig.height=7}

make_diff_percent_dt <- function(dt, diff_set) {
  
  subset_dt <- map_day_0(
    dcast(dt[variable == diff_set],
    ... ~ variable, value.var='value'))
  subset_dt[, c(diff_set) := factor(get(diff_set))]
  
  subset_dt <- subset_dt[, 
    melt(table(get(diff_set))),
    by=c('car', 'donor', 'day', 'k562', 'well', 'plate')][,
      frac := value/sum(value),
      by=c('car', 'donor', 'day', 'k562', 'well', 'plate')]
  names(subset_dt) <- gsub('V1', 'value', names(subset_dt))
  names(subset_dt) <- gsub('Var1', 'diff', names(subset_dt))
  
  diff_mean_dt <- subset_dt[!is.na(donor), list(
      val_mean= mean(frac), 
      val_sd= sd(frac)), 
      by=c('car','k562','donor','day','diff')]

  return(diff_mean_dt)
}

cd62_cd45ra_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd62_cd45ra_diff')
cd45ra_ccr7_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd45ra_ccr7_diff')
cd45ro_ccr7_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd45ro_ccr7_diff')
cd45ro_cd27_diff_dt <- make_diff_percent_dt(diff_marker_dt, 'cd45ro_cd27_diff')
cd27_dt <- make_diff_percent_dt(diff_marker_dt, 'cd27')
cd95_dt <- make_diff_percent_dt(diff_marker_dt, 'cd95')


plot_by_day <- function(diff_mean_dt, title) {
  return(ggplot(diff_mean_dt) + 
      geom_bar(aes(x=as.factor(day), y=val_mean, fill=diff), stat='identity', position='stack') +
      facet_grid(k562+donor~car) + 
    theme_minimal(base_size=18) + 
    labs(x='Day', y='% Subset', title=title))
}

line_plot_by_day <- function(diff_mean_dt, title) {
  return(ggplot(diff_mean_dt, 
      aes(x=as.factor(day), y=val_mean, color=car, group=car, 
          ymax=val_mean+val_sd, ymin=val_mean-val_sd)) + 
    geom_line() + geom_point(size=2) + geom_linerange() +
    facet_grid(k562+diff~donor) + 
    scale_color_brewer(palette='Dark2') +
    theme_minimal(base_size=18))
}

plot_by_car <- function(diff_mean_dt, title) {
  return(ggplot(diff_mean_dt[car != 'untrans']) + 
      geom_bar(aes(x=car, y=val_mean, fill=diff), stat='identity', position='stack') +
      facet_grid(k562+donor~day) + 
    theme_minimal(base_size=18) + 
    labs(x='Day', y='% Subset', title=title) + 
    coord_flip())
}

plot_by_day(cd62_cd45ra_diff_dt[k562=='cd19+'], 'CD62L vs CD45RA differentiation')
plot_by_day(cd45ra_ccr7_diff_dt[k562=='cd19+'], 'CD45RA vs CCR7 differentiation')
plot_by_day(cd45ro_ccr7_diff_dt[k562=='cd19+'], 'CD45RO vs CCR7 differentiation')
    
plot_by_car(cd62_cd45ra_diff_dt[k562=='cd19+'], 'CD62L vs CD45RA differentiation')
plot_by_car(cd45ra_ccr7_diff_dt[k562=='cd19+'], 'CD45RA vs CCR7 differentiation')
plot_by_car(cd45ro_ccr7_diff_dt[k562=='cd19+'], 'CD45RO vs CCR7 differentiation')

plot_by_car(cd45ro_cd27_diff_dt[k562=='cd19+'], 'CD45RO vs CD27 differentiation')
```

```{r, fig.width=18, fig.height=14}
plot_by_day(cd27_dt, title= '% CD27 positive')
plot_by_car(cd27_dt, title= '% CD27 positive')

line_plot_by_day(cd27_dt[diff==T & car != 'KLRG1'], title= '% CD27 positive')

line_plot_by_day(cd95_dt[diff==T], title= '% CD95 positive')
```

# Plots for Kole 8/13

```{r, fig.width=18, fig.height=7}

cd27_dt_subset <- cd27_dt[k562=='cd19+' & diff == T &
  car %in% c('41BB','CD28','BAFF-R','CD40','untrans')][,
    car := factor(
      car,
      levels(factor(car))[c(3,1,2,4,5)],
      labels=c(levels(factor(car))[c(3,1,2,4)],'Untransduced'))]

ggplot(cd27_dt_subset) + 
    geom_bar(aes(x=as.factor(day), y=val_mean, fill=diff), stat='identity', position='stack') +
    facet_grid(donor~car) + 
    theme_minimal(base_size=18) + 
    labs(x='Day', y='Fraction of Cells', title='CD45RO vs CCR7 differentiation') +
    scale_y_continuous(expand=c(0,0), labels = percent_format(accuracy = 1)) + 
    scale_x_discrete(expand=c(0,0)) +
    scale_fill_brewer('Differentiation\nSubset', palette='PiYG', direction=-1) + 
    theme_minimal(base_size=18) + theme(panel.spacing.x = unit(3, "lines")) +
    geom_hline(yintercept=0, size=2) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

ggplot(cd45ro_cd27_diff_dt[k562=='cd19+' & diff == 'CD45RO-/CD27+' & car %in% c('41BB','CD28','BAFF-R','CD40') & day == 33 & donor == 2]) + 
    geom_bar(aes(x=car, y=val_mean, fill=factor(donor)), stat='identity', position='dodge') +
    theme_minimal(base_size=18) +
    labs(x='CAR', y='Fraction of Cells', title='% CD45RO-/CD27+, Day 33') +
    scale_y_continuous(expand=c(0,0), labels = percent_format(accuracy = 1)) + 
    scale_x_discrete(expand=c(0,0)) +
    scale_fill_brewer('Differentiation\nSubset', palette='Paired', direction=-1, guide=F) + 
    theme_minimal(base_size=18) + theme(panel.spacing.x = unit(3, "lines")) +
    geom_hline(yintercept=0, size=2) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

# both donors averaged, car subset only
# for kole 8/13

cd45ro_ccr7_diff_subset_dt <- cd45ro_ccr7_diff_dt[k562=='cd19+' & 
  car %in% c('41BB','CD28','BAFF-R','CD40','untrans')][,
    car := factor(
      car,
      levels(factor(car))[c(3,1,2,4,5)],
      labels=c(levels(factor(car))[c(3,1,2,4)],'Untransduced'))]

ggplot(cd45ro_ccr7_diff_subset_dt[, val_comb := mean(val_mean, na.rm=T), by=c('day','diff','car')]) + 
    geom_bar(aes(x=as.factor(day), y=val_comb/2, fill=diff), stat='identity', position='stack') +
    facet_grid(.~car) + 
    theme_minimal(base_size=18) + 
    labs(x='Day', y='Fraction of Cells', title='CD45RO vs CCR7 differentiation') +
    scale_y_continuous(expand=c(0,0), labels = percent_format(accuracy = 1)) + 
    scale_x_discrete(expand=c(0,0)) +
    scale_fill_brewer('Differentiation\nSubset', palette='PiYG', direction=-1) + 
    theme_minimal(base_size=18) + theme(panel.spacing.x = unit(3, "lines")) +
    geom_hline(yintercept=0, size=2) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```
