---
title: "PCA Analysis for Differentiation Samples"
output:
  html_document:
    df_print: paged
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here('..','html'))})
---


# Load Data 
```{r}
library(ggplot2)
library(data.table)
library(scales)
library(RColorBrewer)
library(reticulate)
#library(uwot)
library(gridExtra)
#library(spatstat)
#use_condaenv(condaenv = 'r-reticulate', required = TRUE)
library(ggsci)

data_dir <- here::here('..','data')
load(file.path(data_dir, 'diff.sampled.Rdata'))
#diff_dt <- fread(file.path(data_dir, 'diff.sampled.csv.gz'))

# map day 0 to both plus and minus
map_day_0 <- function(df) {
  return(rbind(
    df[k562!='none'],
    df[day==0][, k562 := 'cd19+'],
    df[day==0][, k562 := 'cd19-']
  ))
}
```

# PCA
```{r}

# making new table with means & sd for each sample (across donors & replicates. no untrans.) for each variable (except for zombie & cd)
diff_means_dt <- diff_dt[!is.na(day) & !is.na(donor) & !is.na(value) & !(variable %in% c('zombie_t','cd_t')) & car!='untrans', 
  list(m= mean(value), sd= sd(value), n= .N), 
  by=c('day','car','k562','t_type','variable')]

# dcast = opposite of melt
diff_cast_dt <- dcast(diff_means_dt[!is.na(m) & n > 20], 
  day + car + k562 + t_type ~ variable, 
  value.var=c('m','sd'))

diff_cast_dt <- map_day_0(diff_cast_dt)

# diff_cast_m <- dcast(diff_means_dt[!is.na(m) & n > 20], 
#   day + donor + car + k562 + t_type ~ variable, 
#   value.var=c('m'))

# actual principal component analysis
diff_pca <- prcomp(diff_cast_dt[,-c(1:5)], scale. = T, center = T)


ggplot(data.table(diff_pca$x), aes(x=PC1, y=PC2)) + geom_point()


# getting pca for cd19- only, cd19+ only, cd4 cd19+ only, cd8 cd19+ only with sd
neg_cast_dt <- diff_cast_dt[k562=='cd19-']
pos_cast_dt <- diff_cast_dt[k562=='cd19+']
cd4_cast_dt <- diff_cast_dt[t_type=='cd4' & k562=='cd19+']
cd8_cast_dt <- diff_cast_dt[t_type=='cd8' & k562=='cd19+']

neg_pca <- prcomp(neg_cast_dt[,-c(1:5)], scale. = T, center = T)
pos_pca <- prcomp(pos_cast_dt[,-c(1:5)], scale. = T, center = T)
cd4_pca <- prcomp(cd4_cast_dt[,-c(1:5)], scale. = T, center = T)
cd8_pca <- prcomp(cd8_cast_dt[,-c(1:5)], scale. = T, center = T)


# cbind these pca with original table
diff_cbind_dt <- cbind(diff_cast_dt, data.table(diff_pca$x))
neg_cbind_dt <- cbind(neg_cast_dt, data.table(neg_pca$x))
pos_cbind_dt <- cbind(pos_cast_dt, data.table(pos_pca$x))
cd4_cbind_dt <- cbind(cd4_cast_dt, data.table(cd4_pca$x))
cd8_cbind_dt <- cbind(cd8_cast_dt, data.table(cd8_pca$x))


# plot these altogether w/ gridExtra
a <- ggplot(diff_cbind_dt, aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=car)) +
  labs(title='general PCA')
b <- ggplot(pos_cbind_dt, aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=car)) +
  labs(title='CD19+ only PCA')
c <- ggplot(neg_cbind_dt, aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=car)) +
  labs(title='CD19- only PCA')
d <- ggplot(cd4_cbind_dt, aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=car)) +
  labs(title='CD4 only PCA')
e <- ggplot(cd8_cbind_dt, aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=car)) +
  labs(title='CD8 only PCA')

grid.arrange(a, b, c, d, e, ncol=2)


# use cbind to add PCs to original diff_cast_dt
# use pc2/3 instead of 1/2
# rank input vars against which PCs they contribute to
# plot points by car, day, donor, etc
# connect points up by day (bonus points: use directional arrows by day)

```

# 
```{r}

# scree plot of different PCs -- this just checks quality(?). PC1 should have highest variance
screeplot(diff_pca, npcs=length(diff_pca$sdev))
screeplot(pos_pca, npcs=length(pos_pca$sdev))
screeplot(neg_pca, npcs=length(neg_pca$sdev))
screeplot(cd4_pca, npcs=length(cd4_pca$sdev))
screeplot(cd8_pca, npcs=length(cd8_pca$sdev))


# getting list of input variables as data.table
rotation_rows <- data.table(row.names(diff_pca$rotation))
setnames(rotation_rows, "V1", "input_var")

cd4_rotation_rows <- data.table(row.names(cd4_pca$rotation))
cd8_rotation_rows <- data.table(row.names(cd8_pca$rotation))
cd19_rotation_rows <- data.table(row.names(cd19_pca$rotation))

# function to change column name of V1 to input_var
input_names <- function(df) {
  setnames(df, "V1", "input_var")
}

input_names(cd4_rotation_rows)
input_names(cd8_rotation_rows)
input_names(cd19_rotation_rows)


# cbind variances with input variable names
rotation_dt <- cbind(rotation_rows, data.table(diff_pca$rotation))
cd4_rot_dt <- cbind(cd4_rotation_rows, data.table(cd4_pca$rotation))
cd8_rot_dt <- cbind(cd8_rotation_rows, data.table(cd8_pca$rotation))
cd19_rot_dt <- cbind(cd19_rotation_rows, data.table(cd19_pca$rotation))

# rank input variables against which PCs they contribute to
# adds new column of which PC has highest rotation for each input variable
rotation_dt[, highest_pc := names(rotation_dt[, 2:ncol(rotation_dt)])[max.col(abs(rotation_dt[, 2:ncol(rotation_dt)]))]]

rotation_dt[, c("input_var", "highest_pc")]

# ordering input variables for top 3 PCs by absolute value
pc1_dt <- rotation_dt[, 1:2][order(-abs(PC1)), ]
pc2_dt <- rotation_dt[, c(1,3)][order(-abs(PC2)), ]
pc3_dt <- rotation_dt[, c(1,4)][order(-abs(PC3)), ]


# plot each PC to see what input variables contribute to which PC
ggplot() + 
  geom_bar(data=melt(cd8_rot_dt, id.vars='input_var', variable.name='PC', value.name='value'),
           aes(x=reorder(input_var, value), y=value), stat="identity") +
  facet_wrap(~ PC) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# just PC1 in ascending order, but we care about max abs values (i.e. leftmost & rightmost) b/c that contributes most to the variance
ggplot(cd8_rot_dt, aes(x=reorder(input_var, PC1), y=PC1)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle=90, hjust=1))


```


# general PCA plots
```{r}

# cd19+ vs. t_type
ggplot(diff_cbind_dt[k562=='cd19+' & t_type=='cd4'], aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=car, size=1)) +
  scale_color_npg() +
  labs(title="PCA - CD4 CD19+") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))

ggplot(diff_cbind_dt[k562=='cd19+' & t_type=='cd8'], aes(x=PC2, y=PC3)) + 
  geom_point(aes(color=car, shape=as.factor(donor), size=1)) +
  scale_color_npg() +
  labs(title="PCA - CD8 CD19+") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))


# cd19- vs. t_type
ggplot(diff_cbind_dt[k562=='cd19-' & t_type=='cd4'], aes(x=PC2, y=PC3)) + 
  geom_point(aes(color=car, shape=as.factor(donor), size=1)) +
  scale_color_npg() +
  labs(title="PCA - CD4 CD19-") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))

ggplot(diff_cbind_dt[k562=='cd19-' & t_type=='cd8'], aes(x=PC2, y=PC3)) + 
  geom_point(aes(color=car, shape=as.factor(donor), size=1)) +
  scale_color_npg() +
  labs(title="PCA - CD8 CD19-") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))


# facet plots
ggplot(diff_cbind_dt, aes(x=PC2, y=PC3)) + 
  geom_point(aes(color=car, shape=as.factor(donor))) +
  scale_color_npg() +
  labs(title="PCA - PC2/PC3") +
  facet_grid(t_type + k562 ~ day) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))

ggplot(diff_cbind_dt, aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=car, shape=as.factor(donor))) +
  scale_color_npg() +
  labs(title="PCA - PC1/PC2") +
  facet_grid(t_type + k562 ~ day) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))

ggplot(diff_cbind_dt[k562=='cd19+'], aes(x=PC2, y=PC3)) + 
  geom_point(aes(color=car, shape=as.factor(donor))) +
  scale_color_npg() +
  labs(title="PCA - CD19+") +
  facet_grid(t_type + k562 ~ day) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))



```


# cd19- only, cd19+ only, cd4 only, cd8 only PCA plots for comparisons
```{r}

# connecting points by day

diff_days <- c(0, 6, 15, 24, 33)

# using function map_day_0 to add in day 0 points
diff_cbind_dt <- map_day_0(diff_cbind_dt)
neg_cbind_dt <- map_day_0(neg_cbind_dt)
pos_cbind_dt <- map_day_0(pos_cbind_dt)
cd4_cbind_dt <- map_day_0(cd4_cbind_dt)
cd8_cbind_dt <- map_day_0(cd8_cbind_dt)

# new tables for geom_segment
cd8_seg_1 <- cd8_cbind_dt[day != 33][, c('day', 'car', 'k562', 't_type', 'PC1', 'PC2', 'PC3')]
colnames(cd8_seg_1)[colnames(cd8_seg_1) %in% c("day", "PC1", "PC2", "PC3")] <- c("day_a", "PC1_a", "PC2_a", "PC3_a")
cd8_seg_1[, day_b := diff_days[match(day_a, diff_days)+1]]

cd8_seg_2 <- cd8_cbind_dt[day != 0][, c('day', 'car', 'k562', 't_type', 'PC1', 'PC2', 'PC3')]
colnames(cd8_seg_2)[colnames(cd8_seg_2) %in% c("day", "PC1", "PC2", "PC3")] <- c("day_b", "PC1_b", "PC2_b", "PC3_b")

cd8_seg_dt <- merge(cd8_seg_1, cd8_seg_2, by=c('day_b','car','k562','t_type'))


ggplot(cd8_cbind_dt[k562=='cd19+'], aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=as.factor(day), size=1)) +
  geom_segment(data=cd8_seg_dt[k562=='cd19+'], 
               color='grey70',
               aes(x=PC1_a, y=PC2_a, xend=PC1_b, yend=PC2_b),
               arrow=arrow(length=unit(0.3,"cm"))) +
  scale_color_brewer(palette='OrRd') +
  labs(title="CD8 only PCA - CD19+") +
  facet_grid(k562 ~ car) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))


ggplot(cd8_cbind_dt[k562=='cd19+'], aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=car, shape=as.factor(donor), size=1)) +
  geom_segment(data=cd8_seg_dt[k562=='cd19+'], 
               aes(x=PC1_a, y=PC2_a, xend=PC1_b, yend=PC2_b, color=car, alpha=0.1),
               arrow=arrow(length=unit(0.3,"cm"))) +
  scale_color_npg() +
  labs(title="CD8 only PCA - CD19+") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        axis.title = element_text(size=20))


# car %in% c('41BB','BAFF-R','CD28','CD40','KLRG1')

```

