---
title: "Exhaustion Plots for Arrayed Screens"
output:
  html_document:
    df_print: paged
---

# Load Data 
```{r}
library(ggplot2)
library(data.table)
library(scales)
library(RColorBrewer)

data_dir <- here::here('..','data')
load(file.path(data_dir, 'exh.sampled.Rdata'))

car_set <- c('41BB','CD28','BAFF-R','CD40','TACI')


# map day 0 to both plus and minus
map_day_0 <- function(df) {
  return(rbind(
    df[k562!='none'],
    df[k562=='none'][, k562 := 'cd19+'],
    df[k562=='none'][, k562 := 'cd19-']
  ))
}

# some replicates appear to be incorrect - possibly due to evaporation or error in measurement.
# we will identify which wells are way off of the median value for the set of 3 replicates:
exh_means <- exh_dt[grep('_t',variable) & !is.na(donor), list(
  mean_val=mean(value, na.rm=T)),
  by=c('well','plate','day','variable','donor','row','col','k562','car','t_type')]

exh_means[, c('med_val','med_diff') := list(median(mean_val), (mean_val-median(mean_val))/median(mean_val)),
  by=c('day','car','k562','variable','donor','t_type')]

replicate_issue_plot <- ggplot(map_day_0(exh_means)) + geom_histogram(aes(x=abs(med_diff), fill=factor(col %% 3), y=..density..)) + facet_grid(donor + day ~ variable + t_type + k562) + labs(x='% Difference of each replicate from median', y='Measurements') + scale_fill_discrete('replicate #') + scale_x_continuous(labels=label_percent(), oob=scales::oob_squish, limits=c(0,0.33), breaks=c(0,0.30)) + theme_minimal() + theme(panel.grid=element_blank(), panel.border = element_rect(fill=NA, color='grey50')) + geom_vline(xintercept=0.25, linetype=2, color='grey50')

exh_means[, oob := abs(med_diff) >= 0.25]
exh_means[, n_oob := sum(oob), list(donor,k562,day,t_type,car,well,plate,variable)]

outlier_wells <- unique(exh_means[n_oob == 1, list(donor,k562,day,t_type,car,well,plate)])

exh_dt <- outlier_wells[, outlier_well := T][exh_dt, on=.(donor,k562,day,t_type,car,well,plate)]
exh_dt[is.na(outlier_well), outlier_well := F]
```

## Assess Marker Thresholds

```{r fig.width=14, fig.height=8}
# table of thresholds chosen
marker_thresholds <- rbind(
    c(setNames(unlist(exh_opt_cd4$marker_thresholds), names(exh_opt_cd4$marker_thresholds)), t_type='cd4'),
    c(setNames(unlist(exh_opt_cd8$marker_thresholds), names(exh_opt_cd8$marker_thresholds)), t_type='cd8'))
marker_thresholds <- data.table(melt(
    data.table(marker_thresholds), id.vars=c('t_type')))
marker_thresholds <- rbind(
    copy(marker_thresholds[, k562 := 'cd19+']), 
    copy(marker_thresholds[, k562 := 'cd19-']))

blue_shades <- brewer.pal(7, "YlGnBu")[3:7]

# assess marker thresholds
all_marker_data <- map_day_0(exh_dt)[k562 %in% c('cd19+','cd19-') & variable != 'zombie_t' & 
    variable %in% names(exh_opt_cd4$marker_thresholds)]

# remove values < 1% or > 99.9%
all_marker_data <- all_marker_data[
  all_marker_data[, {
    limits=quantile(value,c(.01,.999), na.rm=T);
    list(min=limits[1], max=limits[2])}, by=.(variable)], on='variable'][
  value > min & value < max]

marker_display_data <- rbind(
    all_marker_data[car %in% c('41BB','CD28','zeta','BAFF-R','TACI','CD40','TNR8')][
      , day_lbl := as.character(day)],
    all_marker_data[day == 0 & car == 'untrans'][, day_lbl := 'Untransduced'])[
      k562 == 'cd19+']

ggplot(marker_display_data[variable %in% c('cd39_t','lag3_t','pd1_t','tim3_t')][, variable_lbl := toupper(gsub('_t','',variable))]) + 
    geom_density(aes(x=value, color=factor(day_lbl, levels=c('Untransduced',0,6,15,24,33)))) + 
    theme_minimal() +
    geom_vline(data=marker_thresholds[variable %in% c('cd39_t','lag3_t','pd1_t','tim3_t')][, variable_lbl := toupper(gsub('_t','',variable))], aes(xintercept=value), alpha=0.3, linetype=2) +
    facet_grid(t_type~variable_lbl, scale='free') + 
    scale_color_manual('Day',values=c('grey50',blue_shades)) +
    geom_vline(xintercept=-Inf) + geom_hline(yintercept=-Inf)

```

## Two Marker Contour Plots

```{r}

cast_vars <- function(df, cast_vars) {
  return(
    dcast(map_day_0(df[variable %in% cast_vars]), 
      well + plate + day + car + k562 + donor + event_id + t_type ~ variable,
      value.var='value'))
}

plot_2d_density_vars_split_donor <- function(df, x_var, y_var, tile=F) {

  cast_dt <- data.table(cast_vars(df, cast_vars=c(x_var, y_var)))
  
  x_thresholds <- marker_thresholds[variable==x_var][, list(x_thresh=value), by=c('t_type','k562')]
  y_thresholds <- marker_thresholds[variable==y_var][, list(y_thresh=value), by=c('t_type','k562')]
  
  thresholds <- merge(x_thresholds, y_thresholds, on=c('t_type','k562'))
  
  thresh_dt <- thresholds[cast_dt, on=c('t_type','k562')][, melt(table(
    x_thresh= (get(x_var) > x_thresh),
    y_thresh= (get(y_var) > y_thresh))),
    by=c('k562','car','donor')]
  
  thresh_line_dt <- unique(
    thresholds[cast_dt, on=c('t_type','k562')][, list(x_thresh, y_thresh, k562,t_type)])
  
  thresh_dt[, frac := value/sum(value), by=c('k562','car','donor')]
  thresh_dt[, pct := percent(frac,accuracy=1)]

  quadrant_labels <- data.table(
    x=c(Inf,Inf,-Inf,-Inf),
    y=c(Inf,-Inf,Inf,-Inf),
    x_thresh=c(T, T, F, F),
    y_thresh=c(T, F, T, F),
    hjust=c(1,1,0,0),
    vjust=c(1,0,1,0)
  )
  
  thresh_dt <- thresh_dt[quadrant_labels, on=c('x_thresh','y_thresh')]
  
  if (tile) {
  
    tile_plot <- ggplot(thresh_dt, aes(y=y_thresh, x=x_thresh)) + 
      geom_tile(aes(fill=frac)) + 
      facet_grid(k562+donor~car) + 
      scale_fill_distiller(palette='Greens', direction=1) + 
      geom_text(aes(label=pct), size=3) +
      scale_x_discrete(x_var, labels=c('-','+')) +
      scale_y_discrete(y_var, labels=c('-','+')) +
      theme_minimal()
    
    return(tile_plot)
  } else {
    plot <- ggplot(cast_dt) + 
      geom_density2d(aes(y=get(y_var), x=get(x_var)), n=200) + 
      facet_grid(k562+donor~car) + 
      scale_x_continuous(x_var, limits=c(-1000,4000)) + 
      scale_y_continuous(y_var, limits=c(-1000,4000)) + 
      geom_vline(data=thresh_line_dt, aes(xintercept=as.numeric(x_thresh))) + 
      geom_hline(data=thresh_line_dt, aes(yintercept=as.numeric(y_thresh))) + 
      geom_text(data=thresh_dt, aes(x=x, y=y, label=pct, hjust=hjust, vjust=vjust))
    
    return(plot)
  }
}

tile_set <- function(df, exh_x, exh_y, days=c(6,15,24,33)) {
  plot_grid(
    plot_grid(plotlist=lapply(days, function(day_i) 
      plot_2d_density_vars_split_donor(
        df[t_type == 'cd4' & day==day_i], 
        y_var=exh_x, x_var=exh_y, tile=T) + 
        ggtitle(paste('CD4 Day', day_i))), ncol=1),
    plot_grid(plotlist=lapply(days, function(day_i) 
      plot_2d_density_vars_split_donor(
        df[t_type == 'cd8' & day==day_i], 
        y_var=exh_x, x_var=exh_y, tile=T) + 
        ggtitle(paste('CD8 Day', day_i))), ncol=1)
  )
}

tile_set(df=map_day_0(exh_dt)[k562 == 'cd19+' & car %in% c('41BB','BAFF-R','CD28')], 'pd1_t','lag3_t', days=c(0, 6,15,24,33))


```

## Summary Stats by MFI, % Positive, and % Positive MFI

```{r, fig.width=14, fig.height=8}

# which markers for which summary stats
total_mfi <- c('cd39_t','myc_t', 'pd1_t')
pos_mfi <- c('tim3_t','lag3_t','cd39_t','pd1_t')
pos_pct <- c('tim3_t','lag3_t','cd39_t', 'pd1_t')

pct_pos_markers <- exh_dt[variable %in% pos_pct,
  list(pct_pos= sum(gt_thresh)/.N),
  by=c('plate','well','day','k562','donor','car','variable','t_type')][, 
    list(mean_pct_pos= mean(pct_pos), sd_pct_pos= sd(pct_pos)),
    by=c('day','k562','donor','car','variable','t_type')]
pct_pos_markers <- map_day_0(pct_pos_markers)

pos_mfi_markers <- exh_dt[variable %in% pos_mfi,
  list(pos_mfi_well= mean(value[gt_thresh==T]), pos_mfi_well_sd= sd(value[gt_thresh==T])), 
  by=c('plate','well','day','k562','donor','car','variable','t_type')][,
    `:=`(mean_mfi_pos= mean(pos_mfi_well), sd_mfi_pos= sd(pos_mfi_well)),
        by=c('day','k562','donor','car','variable','t_type')]  
    
pct_pos_markers[, mean_diff_pct_pos := mean_pct_pos-mean(mean_pct_pos, na.rm=T), 
    by=c('day','k562','donor','variable','t_type')]

pct_pos_lbls <- pct_pos_markers[!is.na(variable) & !is.na(donor) & k562 == 'cd19+',
  list(var_mean = mean(mean_pct_pos, na.rm=T)), by=c('k562','day','variable','donor','t_type')][,
    variable := as.character(variable)]

# all CARs, CD19+ only

ggplot(pct_pos_markers[!is.na(variable) & !is.na(donor) & k562 == 'cd19+' & variable %in% pos_pct]) + 
    geom_bar(aes(x=car, y=mean_diff_pct_pos, fill=variable), stat='identity') +
    geom_linerange(aes(x=car, ymin=mean_diff_pct_pos-sd_pct_pos, ymax=mean_diff_pct_pos+sd_pct_pos)) +
    geom_text(data=pct_pos_lbls, 
        aes(label=percent(round(var_mean,3))), y=Inf, x=-Inf, hjust=0, vjust=1) + 
    facet_grid(variable+donor~day+t_type, scales='free') +
    theme_minimal(base_size=18) + scale_y_continuous(labels = percent_format(accuracy = 1)) +
    theme(axis.text.x=element_text(angle = 90, hjust = 1)) +
    labs(x='CAR', y='Change in % Positive', title='Pct % in Exhaustion Marker from Average CAR (All CARs)') +
    geom_hline(yintercept=0) +
    geom_vline(xintercept=-Inf)

# selected car set only, CD19+ only

pct_pos_markers[car %in% car_set, mean_diff_pct_pos := mean_pct_pos-mean(mean_pct_pos, na.rm=T), 
    by=c('day','k562','donor','variable','t_type')]

pct_pos_lbls <- pct_pos_markers[car %in% car_set & !is.na(variable) & !is.na(donor) & k562 == 'cd19+',
  list(var_mean = mean(mean_pct_pos, na.rm=T)), by=c('k562','day','variable','donor','t_type')][,
    variable := as.character(variable)]

ggplot(pct_pos_markers[car %in% car_set & !is.na(variable) & !is.na(donor) & k562 == 'cd19+' & variable %in% pos_pct]) + 
    geom_bar(aes(x=car, y=mean_diff_pct_pos, fill=variable), stat='identity') +
    geom_linerange(aes(x=car, ymin=mean_diff_pct_pos-sd_pct_pos, ymax=mean_diff_pct_pos+sd_pct_pos)) +
    geom_text(data=pct_pos_lbls, 
        aes(label=percent(round(var_mean,3))), y=Inf, x=-Inf, hjust=0, vjust=1) + 
    facet_grid(variable+donor~t_type + day, scales='free') +
    theme_minimal(base_size=18) + scale_y_continuous(labels = percent_format(accuracy = 1)) +
    theme(axis.text.x=element_text(angle = 90, hjust = 1)) +
    labs(x='CAR', y='Change in % Positive', title='Pct % in Exhaustion Marker from Average CAR (Selected CARs)') +
    geom_hline(yintercept=0) +
    geom_vline(xintercept=-Inf)

```

## Number of positive markers per cell

```{r,  fig.width=18, fig.height=7}
marker_ct <- exh_dt[variable %in% c('tim3_t','lag3_t','cd39_t', 'pd1_t'),
  list(n_pos_marker= sum(gt_thresh)), 
  by=c('well','plate','day','Time','car','donor','k562','t_type')]

marker_ct <- marker_ct[, N := .N, by=c('well','plate','day','car','k562','t_type')][N > 1]

marker_ct <- map_day_0(marker_ct)

marker_freq <- marker_ct[, data.frame(table(factor(n_pos_marker, levels= 0:4))), 
  by=c('well','plate','day','car','donor','k562','t_type')]
names(marker_freq)[names(marker_freq) == 'Var1'] <- 'n_pos_marker'

marker_freq[ n_pos_marker != 7, pct := Freq/sum(Freq), 
  by=c('well','plate','day','car','donor','k562','t_type')]

marker_freq <- marker_freq[,
  list(mean_pct= mean(pct, na.rm=T)),
  by=c('day','car','donor','k562', 'n_pos_marker','t_type')]

ggplot(marker_freq[k562 != 'none' & n_pos_marker != 7]) + 
  geom_bar(aes(x=car, y=mean_pct, fill=n_pos_marker), stat='identity') + 
  facet_grid(k562 + donor + t_type ~ day, scales='free') + 
  scale_y_continuous(expand=c(0,0)) + 
  scale_fill_brewer('Number of Exh.\nMarkers Present', palette='YlOrRd') + 
  theme_minimal() +
  labs(x="CAR", y='Fraction of Cells')

ggplot(marker_freq[k562 != 'none' & n_pos_marker != 7 & k562 == 'cd19+']) + 
  geom_bar(aes(x=factor(day), y=mean_pct, fill=n_pos_marker), stat='identity', width=1) + 
  facet_grid(donor ~ t_type + car, scales='free') + 
  scale_y_continuous(expand=c(0,0), labels = percent_format(accuracy = 1)) + 
  scale_x_discrete(expand=c(0,0)) +
  scale_fill_brewer('Number of Exh.\nMarkers Present', palette='YlOrRd') + 
  theme_minimal() +
  geom_vline(xintercept=0:7-0.5) +
  geom_hline(yintercept=c(0,1)) +
  labs(x="CAR", y='Fraction of Cells')
```

## pct marker positive per car

```{r}

#% GFP positive
# ggplot(exh_dt[car != '' & variable == 'gfp_t', sum(gt_thresh)/.N, by=c('well','plate','day','car','donor','k562','t_type')]) + geom_point(aes(x=car, y=V1, shape=factor(donor), color=car)) + facet_grid(k562~t_type + day) + scale_color_manual(values=c(car_colors, 'untrans'='grey')

marker_ct <- exh_dt[!outlier_well & variable %in% c('tim3_t','lag3_t','cd39_t', 'pd1_t'),
  list(n_pos_marker= sum(gt_thresh)),
  by=c('well','plate','day','Time','car','donor','k562','t_type')]

# gfp_pos <- exh_dt[car != '' & variable == 'gfp_t' & gt_thresh == T, list(
#     well,plate,day,event_id)]

marker_ct <- marker_ct[, N := .N, by=c('well','plate','day','car','k562','t_type')][N > 1]

marker_ct <- map_day_0(marker_ct)

marker_freq <- marker_ct[, data.frame(table(factor(n_pos_marker, levels= 0:4))), 
  by=c('well','plate','day','car','donor','k562','t_type')]
names(marker_freq)[names(marker_freq) == 'Var1'] <- 'n_pos_marker'

marker_freq[ n_pos_marker != 7, pct := Freq/sum(Freq), 
  by=c('well','plate','day','car','donor','k562','t_type')]

# marker_freq <- marker_freq[,
#   list(mean_pct= mean(pct, na.rm=T)),
#   by=c('day','car','donor','k562', 'n_pos_marker','t_type')]

make_day_plot <- function(plot_day) {

  day_dt <- marker_freq[car %in% c('41BB','CD28','BAFF-R') & day %in% plot_day & k562 == 'cd19+'][, 
      c('mean_pct','sd_pct') := list(mean(pct), sd(pct)), 
      by=c('n_pos_marker','t_type','donor','day','k562','car')]
  
  stat.test <- day_dt %>%
    group_by(n_pos_marker, t_type, donor, day) %>%
    t_test(pct ~ car)
  
  stat.test <- stat.test %>% filter(p.adj.signif != 'ns') %>%
    add_xy_position(x = "n_pos_marker", dodge = 0.8)
  
  day_plot <- ggplot(day_dt) + 
    geom_errorbar(aes(x=n_pos_marker, ymin=mean_pct-sd_pct, ymax=mean_pct+sd_pct, group=car), 
      color='black', position=position_dodge(0.8)) +
    geom_bar(aes(x=n_pos_marker, y=mean_pct, color=car, fill=car), 
      position=position_dodge(0.8), stat='identity') +
    facet_grid(day + donor ~ t_type + k562) +
    scale_fill_manual(values=car_colors) +
    scale_color_manual(values=car_colors) +
    scale_y_continuous(labels=scales::label_percent()) +
    stat_pvalue_manual(
      stat.test, label = "p.adj.signif", tip.length = 0.01) +
    theme_minimal() +
    geom_vline(xintercept=-Inf) + 
    geom_hline(yintercept=-Inf) +
    theme(panel.grid=element_blank())

  return(day_plot)
}
  


#line verison
# ggplot(
#   marker_freq[car %in% c('41BB','CD28','BAFF-R','KLRG1','zeta','CD4O','untrans') & day == 15 & k562 == 'cd19+'][, 
#     c('mean_pct','sd_pct') := list(mean(pct), sd(pct)), 
#     by=c('n_pos_marker','t_type','donor','day','k562','car')]) + 
#   geom_linerange(aes(x=n_pos_marker, ymin=mean_pct-sd_pct, ymax=mean_pct+sd_pct, group=car, color=car)) +
#   geom_line(aes(x=n_pos_marker, y=mean_pct, color=car, fill=car, group=car), stat='identity') +
#   facet_grid(day + donor ~ t_type + k562) +
#   scale_fill_manual(values=c(car_colors, 'untrans'='grey')) +
#   scale_color_manual(values=c(car_colors, 'untrans'='grey')) +
#   scale_y_continuous(labels=scales::label_percent()) +
#   theme_minimal() +
#   geom_vline(xintercept=-Inf) + 
#   geom_hline(yintercept=-Inf) +
#   theme(panel.grid=element_blank())

(d6_markers | d15_markers) | plot_layout(guides='collect')

```

```{r fig.height=4.5, fig.width=11.5, units="inches"}
##banff figure

ggplot(marker_freq[k562 != 'none' & n_pos_marker != 7 & n_pos_marker != 0 & k562 == 'cd19+' & car %in% c('CD28', '41BB', 'BAFF-R', 'CD40', 'TACI') & donor == 2][,
    car := factor(car, levels=c('CD28', '41BB', 'BAFF-R', 'CD40', 'TACI'), labels=c('CD28', '41BB', 'Receptor 1', 'Receptor 2', 'Receptor 4'))]) +
    geom_bar(aes(x=factor(day), y=mean_pct, fill=n_pos_marker), stat='identity', width=1) +
    facet_grid(. ~ t_type + car, scales='free') +
    scale_y_continuous(expand=c(0,0), labels = percent_format(accuracy = 1)) +
    scale_x_discrete(expand=c(0,0)) +
    scale_fill_brewer('Number of Exh.\nMarkers Present', palette='Reds') +
    theme_minimal() +
    theme(axis.text=element_text(size=8),
          axis.title=element_text(size=18,face="bold"),
          strip.text.x = element_text(size = 10),
          legend.text=element_text(size=12),
          legend.title=element_text(size=14),
          legend.title.align = 0.5,
          panel.grid = element_blank()) +
    geom_vline(xintercept=0:7-0.5, color="white") +
    geom_hline(yintercept=c(0,1)) +
    labs(x="CAR", y='Fraction of Cells')
```

### Pie Charts, inidividual donors

```{r,  fig.width=10, fig.height=14}

ggplot(marker_freq[donor == 1 & k562 != 'none' & n_pos_marker != 7 & k562 == 'cd19+']) + 
    geom_bar(aes(x=1, y=mean_pct, fill=n_pos_marker), stat='identity', width=1) + 
    facet_grid(t_type + day ~ car) + 
    scale_y_continuous(expand=c(0,0)) + 
    scale_x_discrete(expand=c(0,0)) +
    scale_fill_brewer('Number of Exh.\nMarkers Present', palette='YlOrRd') + 
    theme_minimal() +
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
    geom_vline(xintercept=0:7-0.5) +
        labs(x="CD4/CD8 and Day", y='CAR', title='Fraction of Cells (Donor 1)') +
    coord_polar("y", start=0)

ggplot(marker_freq[donor == 2 & k562 != 'none' & n_pos_marker != 7 & k562 == 'cd19+']) + 
    geom_bar(aes(x=1, y=mean_pct, fill=n_pos_marker), stat='identity', width=1) + 
    facet_grid(t_type + day ~ car) + 
    scale_y_continuous(expand=c(0,0)) + 
    scale_x_discrete(expand=c(0,0)) +
    scale_fill_brewer('Number of Exh.\nMarkers Present', palette='YlOrRd') + 
    theme_minimal() +
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
    geom_vline(xintercept=0:7-0.5) +
    labs(x="CD4/CD8 and Day", y='CAR', title='Fraction of Cells (Donor 2)') +
    coord_polar("y", start=0)
```

### Pie Charts, Mean

Remove day 33 because only donor 1.


```{r, fig.width=10, fig.height=14}

marker_freq_avg <- marker_freq[day < 33, list(mean_pct= mean(mean_pct)), by=c('car', 'k562','n_pos_marker','t_type','day')]

ggplot(marker_freq_avg[k562 == 'cd19+']) + 
    geom_bar(aes(x=1, y=mean_pct, fill=n_pos_marker), stat='identity', width=1) + 
    facet_grid(t_type + day ~ car) + 
    scale_y_continuous(expand=c(0,0)) + 
    scale_x_discrete(expand=c(0,0)) +
    scale_fill_brewer('Number of Exh.\nMarkers Present', palette='YlOrRd') + 
    theme_minimal() +
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
    geom_vline(xintercept=0:7-0.5) +
    labs(x="CD4/CD8 and Day", y='CAR', title='Fraction of Cells (Donor Average)') +
    coord_polar("y", start=0)

```
