---
    title: "tcsl175_exh"
output: html_document
---
    
    ```{r setup, include=FALSE}
library(data.table)
library(scales)
library(here)
library(flowCore)
library(flowWorkspace)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(rstatix)
```

# Define Functions

```{r}
parent_folder = here::here('..','..')

load_platemaps <- function(exh_dir) {
    
    # load platemap filenames
    platemap_paths <- data.table(
        filepath= normalizePath(file.path(exh_dir, list.files(
            exh_dir,
            pattern='tcsl175_r_map.csv',
            recursive=TRUE))))
    
    #load
    platemaps <- platemap_paths[, fread(file=.BY[[1]]), by=filepath]
    
    
    # put 0 back into well number (ugh)
    platemaps[, well := gsub(' ', '',
                             gsub('([A-H])(\\d{1})$', '\\1 0\\2', well_id))]
    
    return(platemaps)
}

exh_dir <- file.path(
    parent_folder,
    "s3-roybal-tcsl/lenti_screen_compiled_data/data/fcs/tcsl175")

load_fcs <- function(exh_dir) {
    exh_fcs_dir <- file.path(exh_dir)
    
    # load fcs filenames
    fcs_paths <- data.table(
        filepath= normalizePath(file.path(exh_fcs_dir, list.files(
            exh_fcs_dir,
            pattern='.*fcs',
            recursive=TRUE))))
    
    # parse well name
    fcs_paths[, well := gsub('.*_([A-H]\\d+).fcs','\\1', filepath)]
    fcs_paths[, t_type := gsub('.*(cd\\d)_[A-H]\\d+.fcs','\\1', filepath)]
    fcs_paths[, tissue := gsub('.*/(\\w+)_cd\\d+_[A-H]\\d+.fcs','\\1', filepath)]
    
    fcs_dt <- fcs_paths[
        !(well == 'B07' & tissue == 'spleen' & t_type == 'cd8') &
            !(well == 'C06' & tissue == 'tumor' & t_type == 'cd4'), 
            as.data.frame(flowCore::exprs(read.FCS(filepath))),
        by=c('well','t_type','tissue')]
    
    # give each event an ID for tracking after melt
    fcs_dt[, event_id := .I, by=c('well','t_type','tissue')]
    
    channel_map <- list(
        cd4="FJComp-586_15 YG-A",
        cd8="FJComp-379_28 UV-A",
        tim3="FJComp-450_50 Violet-A",
        gfp="FJComp-515_20 Blue-A",
        zombie="FJComp-586_15 Violet-A",
        lag3= "FJComp-660_20 Red-A",
        pd1= "FJComp-710_50 Violet-A",
        cd39="FJComp-780_60 Red-A")
    
    # replace column names
    chan_names <- data.table(merge(
        names(fcs_dt),
        data.table(
            marker=names(channel_map),
            chan=unlist(channel_map)), 
        by.x='x', by.y='chan',
        all=T))
    
    # fill in original column names
    chan_names[is.na(marker), marker := x]
    
    # rename columns and melt
    names(fcs_dt) <- chan_names[
        names(fcs_dt), marker, on='x']
    
    return(list(fcs_dt= fcs_dt, channel_map= channel_map))
}


load_exh_data <- function(experiment_dir, marker_pos_threshold, max_sample=Inf) {
    
    exh_dir <- file.path(parent_folder, experiment_dir)
    
    platemaps <- load_platemaps(exh_dir)
    
    fcs_out <- load_fcs(exh_dir)
    fcs_dt <- fcs_out$fcs_dt
    channel_map <- fcs_out$channel_map
    rm(fcs_out)
    
    fcs_dt <- merge(
        fcs_dt, platemaps,
        on=intersect(names(platemaps), names(fcs_dt)), all=TRUE)
    
    # flowJo transform 
    for (chan_name in c(names(channel_map), 
                        'SSC-A','SSC-W','SSC-H','FSC-A','FSC-H','FSC-W')) { 
        fcs_dt[, c(paste0(chan_name,'_t')) := flowjo_biexp()(fcs_dt[[chan_name]])] 
    }
    
    # downsample per well if specified
    fcs_dt <- fcs_dt[, .SD[sample(.N, min(c(.N, max_sample)))], by=c('well','t_type','tissue')]
    
    melt_cols <- c(names(channel_map), 'SSC-A','SSC-W','SSC-H','FSC-A','FSC-H','FSC-W')
    transformed_vars <- paste0(melt_cols,'_t')
    melt_cols <- c(melt_cols, transformed_vars)
    
    fcs_melt_dt <- melt(
        fcs_dt, 
        measure.vars=melt_cols)
    
    marker_thresh_dt <- data.table(
        variable= paste0(names(marker_pos_threshold)),
        threshold= unlist(marker_pos_threshold))
    
    fcs_melt_dt <- fcs_melt_dt[marker_thresh_dt, on='variable'][, gt_thresh := value > threshold]
    fcs_melt_dt[, threshold := NULL]
    
    return(list(fcs_melt_dt= fcs_melt_dt, channel_map=channel_map, melt_cols=melt_cols))
}

```

## Load Data

```{r}

marker_pos_threshold <- list(
    tim3_t= 400,
    gfp_t=1000,
    zombie_t=750,
    myc_t=1400,
    lag3_t= 700, 
    pd1_t= 1600,
    cd39_t= 1300)

fcs_dir<- "s3-roybal-tcsl/lenti_screen_compiled_data/data/fcs/tcsl175"

exh_out <- load_exh_data(fcs_dir, marker_pos_threshold)

exh_dt <- exh_out$fcs_melt_dt
```

## Plot All events
```{r}

marker_thresholds <- rbind(
    c(setNames(unlist(marker_pos_threshold), names(marker_pos_threshold)), t_type='cd4'),
    c(setNames(unlist(marker_pos_threshold), names(marker_pos_threshold)), t_type='cd8'))
marker_thresholds <- data.table(melt(
    data.table(marker_thresholds), id.vars=c('t_type')))

all_marker_data <- exh_dt[variable != 'zombie_t' & variable %in% names(marker_pos_threshold)]

# remove values < 1% or > 99.9%
all_marker_data <- all_marker_data[
    all_marker_data[, {
        limits=quantile(value,c(.01,.999), na.rm=T);
        list(min=limits[1], max=limits[2])}, by=.(variable)], on='variable'][
            value > min & value < max]

ggplot(all_marker_data[variable %in% c('cd39_t','lag3_t','pd1_t','tim3_t','gfp_t')][, variable_lbl := toupper(gsub('_t','',variable))]) + 
    geom_density(aes(x=value, color=car=='UNT')) + 
    theme_minimal() +
    geom_vline(data=marker_thresholds[variable %in% c('cd39_t','lag3_t','pd1_t','tim3_t','gfp_t')][, variable_lbl := toupper(gsub('_t','',variable))], aes(xintercept=as.numeric(value)), alpha=0.3, linetype=2) +
    facet_grid(t_type~variable_lbl, scale='free') + 
    geom_vline(xintercept=-Inf) + geom_hline(yintercept=-Inf)


```

##  GFP Positive Only
```{r}
# assess marker thresholds
all_marker_data <- exh_dt[variable != 'zombie_t' & variable %in% names(marker_thresholds)]


# subset on GFP positive or UNT events
gfp_pos_events <- exh_dt[variable == 'gfp_t' & (gt_thresh == T | car == 'UNT'), list(t_type, event_id)]
gfp_exh_dt <- exh_dt[gfp_pos_events, on=c('t_type','event_id')]

all_marker_data <- gfp_exh_dt[variable != 'zombie_t' & variable %in% names(marker_pos_threshold)]

# remove values < 1% or > 99.9%
all_marker_data <- all_marker_data[
    all_marker_data[, {
        limits=quantile(value,c(.01,.999), na.rm=T);
        list(min=limits[1], max=limits[2])}, by=.(variable)], on='variable'][
            value > min & value < max]

ggplot(all_marker_data[variable %in% c('cd39_t','lag3_t','pd1_t','tim3_t','gfp_t')][, variable_lbl := toupper(gsub('_t','',variable))]) + 
    geom_density(aes(x=value, color=car=='UNT')) + 
    theme_minimal() +
    geom_vline(data=marker_thresholds[variable %in% c('cd39_t','lag3_t','pd1_t','tim3_t','gfp_t')][, variable_lbl := toupper(gsub('_t','',variable))], aes(xintercept=as.numeric(value)), alpha=0.3, linetype=2) +
    facet_grid(t_type~variable_lbl, scale='free') + 
    geom_vline(xintercept=-Inf) + geom_hline(yintercept=-Inf)

```


## Number of positive markers per cell
```{r}

marker_ct <- all_marker_data[variable %in% c('tim3_t','lag3_t', 'pd1_t'),
  list(n_pos_marker= sum(gt_thresh)), 
  by=c('well','t_type','car','event_id','tissue')]

marker_ct <- marker_ct[, N := .N, by=c('well','t_type','car','tissue')][N > 1]

marker_freq <- marker_ct[, data.frame(table(factor(n_pos_marker, levels= 0:4))), 
  by=c('well','t_type','car','tissue')]

names(marker_freq)[names(marker_freq) == 'Var1'] <- 'n_pos_marker'

marker_freq[, pct := Freq/sum(Freq), 
  by=c('well','t_type','car','tissue')]

marker_freq <- marker_freq[,
  list(mean_pct= mean(pct, na.rm=T)),
  by=c('t_type','car','tissue','n_pos_marker')]

ggplot(marker_freq) + 
  geom_bar(aes(x=car, y=mean_pct, fill=n_pos_marker), stat='identity') + 
  facet_grid(t_type ~ tissue, scales='free') + 
  scale_y_continuous(expand=c(0,0)) + 
  scale_fill_brewer('Number of Exh.\nMarkers Present', palette='YlOrRd') + 
  theme_minimal() +
  labs(x="CAR", y='Fraction of Cells')

```

## pct marker positive per car
```{r}

marker_ct <- all_marker_data[variable %in% c('tim3_t','lag3_t', 'pd1_t'),
  list(n_pos_marker= sum(gt_thresh)), 
  by=c('well','t_type','car','event_id','tissue')]

marker_ct <- marker_ct[, N := .N, by=c('well','t_type','car','tissue')][N > 1]

marker_freq <- marker_ct[, data.frame(table(factor(n_pos_marker, levels= 0:4))), 
  by=c('well','t_type','car','tissue')]

names(marker_freq)[names(marker_freq) == 'Var1'] <- 'n_pos_marker'

marker_freq[, pct := Freq/sum(Freq), 
  by=c('well','t_type','car','tissue')]

make_tissue_plot <- function(plot_tissue) {
    
  tissue_dt <- marker_freq[car %in% c('41BB','CD28','BAFF-R') & tissue %in% plot_tissue][, 
      c('mean_pct','sd_pct') := list(mean(pct), sd(pct)), 
      by=c('n_pos_marker','t_type','car')]
  
  stat.test <- tissue_dt %>%
    group_by(n_pos_marker, t_type) %>%
    t_test(pct ~ car)
 
  stat.test <- stat.test %>% filter(p.adj.signif != 'ns') %>%
    add_xy_position(x = "n_pos_marker", dodge = 0.8)
  
  tissue_plot <- ggplot(tissue_dt) + 
    geom_errorbar(aes(x=n_pos_marker, ymin=mean_pct-sd_pct, ymax=mean_pct+sd_pct, group=car), 
      color='black', position=position_dodge(0.8)) +
    geom_bar(aes(x=n_pos_marker, y=mean_pct, color=car, fill=car), 
      position=position_dodge(0.8), stat='identity') +
    facet_grid(~ t_type) +
    scale_y_continuous(labels=scales::label_percent()) +
    stat_pvalue_manual(
      stat.test, label = "p.adj.signif", tip.length = 0.01) +
    theme_minimal() +
    geom_vline(xintercept=-Inf) + 
    geom_hline(yintercept=-Inf) +
    theme(panel.grid=element_blank())
  return(tissue_plot)
}


#plot each mouse individually by how many markers 
ggplot(tissue_dt, aes(x= n_pos_marker, y=pct, color=car,  fill=car, group=interaction(n_pos_marker, car))) + geom_point(position=position_dodge(1)) + facet_grid(~t_type)


mean_dt <- marker_ct[car %in% c('41BB','CD28','BAFF-R') & tissue %in% plot_tissue][, 
      list('mean_n_pos_markers'=mean(n_pos_marker), 'sd_n_pos_markers'= sd(n_pos_marker), 'n_event'=.N), 
      by=c('well','car','t_type')]


#comparing the mean number of exh markers for each mouse to show distribution across exh spectrum
ggplot(mean_dt[n_event > 150], aes(x=mean_n_pos_markers, y=car,
    color=t_type))+geom_point()

#t test by combining the t cells cd4 and cd8 as two independent points
stat.test <- mean_dt[n_event > 150] %>% 
    t_test(mean_n_pos_markers ~ car)
 
#wilcoxon test for the t cells separated
stat.test <- mean_dt[n_event > 150] %>% group_by(t_type) %>%
    wilcox_test(mean_n_pos_markers ~ car)

stat.test <- stat.test %>% filter(p.adj.signif != 'ns') %>%
    add_xy_position(x = "n_pos_marker", dodge = 0.8)

```



