---
title: "tcsl139_exh"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(
  inputFile, encoding = encoding,
  output_dir = here::here('..','html'))})
---

```{r setup, warning=FALSE, message=FALSE}
setwd(here::here())

library(data.table)
library(scales)
library(here)
library(flowCore)
library(flowWorkspace)
library(ggplot2)

parent_folder = here::here('..','..')

load_platemaps <- function(exh_dir) {
  
  
  # load platemap filenames
  platemap_paths <- data.table(
    filepath= normalizePath(file.path(exh_dir, list.files(
      exh_dir,
      pattern='.*platemap.csv$',
      recursive=TRUE))))
  
  #parse day from file name
  platemap_paths[, day := gsub('.*D(\\d+).*', '\\1', filepath)]
  
  # load and merge platemaps
  platemaps <- platemap_paths[, fread(file=.BY[[1]]), by=filepath]
  
  # put 0 back into well number (ugh)
  platemaps[, well := gsub(' ', '',
    gsub('([A-H])(\\d{1})$', '\\1 0\\2', well))]
  
  return(platemaps)
}

load_fcs <- function(exh_dir) {

  # load fcs filenames
  fcs_paths <- data.table(
    filepath= normalizePath(file.path(exh_dir, list.files(
      exh_dir,
      pattern='.*fcs',
      recursive=TRUE))))
  
  # parse well name
  fcs_paths[, well := gsub('.*_([A-H]\\d+).fcs','\\1', filepath)]
  fcs_paths[, t_type := gsub('.*_(cd\\d+)_[A-H]\\d+.fcs','\\1', filepath)]
  
  fcs_dt <- fcs_paths[, 
                      as.data.frame(flowCore::exprs(read.FCS(filepath))),
                      by=c('well','t_type')]
  
  # give each event an ID for tracking after melt
  fcs_dt[, event_id := .I, by=c('well','t_type')]
  
  channel_map <- list(
    cd8="FJComp-379_28 UV-A",
    gfp="FJComp-515_20 Blue-A",
    tim3="FJComp-586_15 YG-A",
    pd1="FJComp-660_20 Red-A",
    cd4="FJComp-660_20 Violet-A",
    lag3="FJComp-800_30 Violet-A",
    cd39="FJComp-710_50 Violet-A")
  
  # replace column names
  chan_names <- data.table(merge(
    names(fcs_dt),
    data.table(
      marker=names(channel_map),
      chan=unlist(channel_map)), 
    by.x='x', by.y='chan',
    all=T))
  
  # fill in original column names
  chan_names[is.na(marker), marker := x]
  
  # rename columns and melt
  names(fcs_dt) <- chan_names[
    names(fcs_dt), marker, on='x']
  
  # merge unmelted with plate map
  return(list(fcs_dt= fcs_dt, channel_map= channel_map))
}

load_exh_data <- function(experiment_dir, marker_pos_threshold, 
    max_sample=Inf) {
  
  exh_dir <- file.path(parent_folder, experiment_dir)
  
  platemaps <- load_platemaps(exh_dir)
  
  fcs_out <- load_fcs(exh_dir)
  fcs_dt <- fcs_out$fcs_dt
  channel_map <- fcs_out$channel_map
  rm(fcs_out)
  
  fcs_dt <- merge(
    fcs_dt, platemaps,
    on=intersect(names(platemaps), names(fcs_dt)), all=TRUE)
  
  fcs_dt <- fcs_dt[!is.na(exp) & !is.na(filepath)]
  
  # flowJo transform 
  for (chan_name in c(names(channel_map), 
      'SSC-A','SSC-W','SSC-H','FSC-A','FSC-H','FSC-W')) { 
    fcs_dt[, c(paste0(chan_name,'_t')) := flowjo_biexp()(fcs_dt[[chan_name]])] 
  }
  
  # downsample per well if specified
  fcs_dt <- fcs_dt[, 
    .SD[sample(.N, min(c(.N, max_sample)))], by=c('well','t_type')]
  
  melt_cols <- c(names(channel_map), 'SSC-A','SSC-W','SSC-H','FSC-A','FSC-H','FSC-W')
  transformed_vars <- paste0(melt_cols,'_t')
  melt_cols <- c(melt_cols, transformed_vars)
  
  fcs_melt_dt <- melt(
    fcs_dt,
    measure.vars=melt_cols)
  
  marker_thresh_dt <- data.table(
    variable= paste0(names(marker_pos_threshold)),
    threshold= unlist(marker_pos_threshold))
  
  fcs_melt_dt <- fcs_melt_dt[marker_thresh_dt, on='variable'][, 
    gt_thresh := value > threshold][!is.na(filepath) & !is.na(exp)]
  
  fcs_melt_dt[, threshold := NULL]
  
  return(list(
    fcs_melt_dt= fcs_melt_dt, channel_map=channel_map, melt_cols=melt_cols))
}

exh_marker_pos_threshold <- list(
    cd8_t=2100,
    gfp_t=1100,
    tim3_t=1000,
    pd1_t=600,
    cd4_t=2100,
    lag3_t=950,
    cd39_t=1600)

#AWS Version:
exh_dir <- "s3-roybal-tcsl/lenti_screen_compiled_data/data/fcs/tcsl139/exh"

n_events_per_well <- Inf

exh_out <- load_exh_data(exh_dir, 
  exh_marker_pos_threshold, 
  max_sample=n_events_per_well)

```

## Assess Marker Thresholds
```{r, fig.width=15, fig.height=8}
# table of thresholds chosen
marker_thresholds <- data.table(
  variable= as.factor(names(exh_marker_pos_threshold)),
  value=unlist(exh_marker_pos_threshold))

exh_dt <- exh_out$fcs_melt_dt

# assess marker thresholds
ggplot(exh_dt[variable %in% levels(marker_thresholds$variable)]) + 
    geom_density(aes(x=value, color=t_type)) + 
    scale_x_continuous(limits=c(-1000,5000)) + 
    theme_minimal() +
    geom_vline(data=marker_thresholds, 
        aes(xintercept=value)) +
    facet_wrap(~variable, scale='free')
```

## Generate summary stats

```{r}

exh_dt <- exh_dt[
    !is.na(t_type) & 
    !variable %in% c('cd4_t','cd8_t','gfp_t') &
    !is.na(car)]

exh_dt[, dose := factor(dose, labels=c('4.5e6', '10e6'))]

# which markers for which summary stats
total_mfi <- c('cd39_t','myc_t', 'pd1_t')
pos_mfi <- c('tim3_t','lag3_t','cd39_t','pd1_t')
pos_pct <- c('tim3_t','lag3_t','cd39_t', 'pd1_t')

pct_pos_markers <- exh_dt[,
  list(pct_pos= sum(gt_thresh)/.N),
  by=c('well','car','mouse','organ','variable','dose','t_type')][, 
    list(mean_pct_pos= mean(pct_pos), sd_pct_pos= sd(pct_pos)),
    by=c('car','organ','variable','dose','t_type')]

pos_mfi_markers <- exh_dt[,
  list(
    pos_mfi_well= mean(value), 
    pos_mfi_well_sd= sd(value)), 
  by=c('car','organ','variable','dose','t_type')]
    
pct_pos_markers[, mean_diff_pct_pos := mean_pct_pos-mean(mean_pct_pos, na.rm=T), 
    by=c('car','organ','variable','dose','t_type')]

pct_pos_lbls <- pct_pos_markers[,
  list(var_mean = mean(mean_pct_pos, na.rm=T)),
  by=c('car','organ','variable','dose','t_type')][,
    variable := as.character(variable)]
```

## Plot Exh
```{r fig.width=15, fig.height=15}

ggplot(exh_dt) + 
    geom_density(aes(x=value, color=interaction(car, dose))) + 
    scale_x_continuous(limits=c(-1000,5000)) + 
    theme_minimal() +
    geom_vline(
      data=marker_thresholds[!variable %in% c('cd4_t','cd8_t','gfp_t')], 
      aes(xintercept=value)) +
    facet_grid(organ+t_type~variable, scale='free')

ggplot(pct_pos_markers) + 
  geom_bar(aes(x=interaction(car,dose), y=mean_pct_pos, fill=variable, alpha=dose), 
    stat='identity', position=position_dodge2(width = 1, preserve = "single")) +
  scale_alpha_manual(values=c(.6,1)) +
  geom_linerange(aes(
    x=interaction(car,dose), 
    ymin=mean_pct_pos-sd_pct_pos, ymax=mean_pct_pos+sd_pct_pos)) +
  facet_grid(organ+t_type~variable, scale='free') +
  theme_minimal(base_size=18) + 
  scale_y_continuous(labels = percent_format(accuracy = 1), limits=c(0,1)) +
  theme(axis.text.x=element_text(angle = 90, hjust = 1), 
    panel.grid=element_blank()) +
  labs(
    x='CAR', 
    y='% Positive', 
    title='Pct % in Exhaustion Marker from Average CAR (All CARs)') +
  geom_hline(yintercept=0) +
  geom_vline(xintercept=-Inf)

ggplot(pos_mfi_markers) + 
  geom_bar(aes(x=interaction(car,dose), y=pos_mfi_well, fill=variable, alpha=dose), 
    stat='identity', position=position_dodge2(width = 1, preserve = "single")) +
  scale_alpha_manual(values=c(.6,1)) +
  geom_linerange(aes(
    x=interaction(car,dose), 
    ymin=pos_mfi_well-pos_mfi_well_sd, ymax=pos_mfi_well+pos_mfi_well_sd)) +
  facet_grid(organ+t_type~variable, scale='free') +
  theme_minimal(base_size=18) + 
  scale_y_continuous() +
  theme(axis.text.x=element_text(angle = 90, hjust = 1),
    panel.grid=element_blank()) +
  labs(
    x='CAR', 
    y='Mean MFI', 
    title='Mean MFI in Exhaustion Marker from Average CAR (All CARs)') +
  geom_hline(yintercept=0) +
  geom_vline(xintercept=-Inf)
```
