---
title: "tcsl139"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(grid)
library(gtable)
library(RColorBrewer)
library(ggsci)

#paste into terminal tab until Dan fixes this
#s3fs roybal-tcsl ~/s3-roybal-tcsl/ -o passwd_file=${HOME}/.passwd-s3fs

#to make a data table with my csv 
measure.dt <- fread(paste0(
  '/home/ec2-user/s3-roybal-tcsl/lenti_screen_compiled_data/data/csv/',
  'tcsl139_tumor_measurements.csv'))

# change area to numeric - the 'none' cells confused fread, use NA instead.
measure.dt[, Area := as.numeric(Area)]

# # summary for each treatment type
# measure.sum.dt <- measure.dt[, list(
#     mean_area= mean('Area'!= 'none'), 
#     sd_area= sd('Area'!='none')), by=c('Cage','Mouse','Day', 'Treatment')]

ggplot(measure.dt [Area != 'none'], 
       aes(x=as.factor(Day), 
           y=as.numeric(Area), 
           group=interaction(Cage, Mouse), 
           color=Treatment)) + 
    geom_line(linetype="solid", size=1) + 
    geom_point() +
    theme_minimal() +
    scale_color_npg(breaks=c(
      'None','10e6_Zeta','4.5e6_CD28','10e6_41BB','10e6_Unt','4.5e6_41BB')) +
    theme(axis.text.x = element_text(hjust = 0.5),
          text = element_text(size=22),
          axis.title = element_text(size=20),
          legend.title.align = 0.5, 
          plot.title = element_text(hjust = 0.5),
          title = element_text(size = 18)) +
    labs(x='Days Post Tumor Injection', y='Tumor Volume', 
         title='TCSL139 K562 Pilot')

```


```{r}

# plotting average volume
measure.sum.dt <- measure.dt[, `:=` (avg_vol = mean(Area, na.rm=T), 
                                     std_dev = sd(Area, na.rm=T)), 
                             by=c('Day','Treatment')]


ggplot(measure.sum.dt [Area != 'none'], 
       aes(x=as.factor(Day), y=as.numeric(avg_vol), group=interaction(Cage, Mouse),
           color=Treatment)) + 
  geom_line(linetype="solid", size=1) + 
  geom_point() +
  geom_linerange(aes(ymin=avg_vol-std_dev, ymax=avg_vol+std_dev, color=Treatment)) +
  theme_minimal() +
  scale_color_npg(breaks=c(
    'None','10e6_Zeta','4.5e6_CD28','10e6_41BB','10e6_Unt','4.5e6_41BB')) +
  scale_fill_npg(breaks=c(
    'None','10e6_Zeta','4.5e6_CD28','10e6_41BB','10e6_Unt','4.5e6_41BB')) +
  theme(axis.text.x = element_text(hjust = 0.5), 
        legend.title.align=0.5, 
        text = element_text(size=22),
        axis.title = element_text(size=20),
        plot.title = element_text(hjust = 0.5),
        title = element_text(size = 18)) +
  labs(x='Days Post Tumor Injection', 
       y='Tumor Volume', 
       title='TCSL139 K562 Pilot - Average Tumor Volumes')

```

